### ISSUE TITLE
cosmeticscore keep crashes server.

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#100]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

EclipseMC#7777

### What happened?

cosmeticscore keep crashes server.

### Steps to reproduce the issue

i think this crashed is happend by mythicdungeons which create temporary instance dungeon world.

### Server version

Purpur 1.19.2 R0.1 SNAPSHOT

### CosmeticsCore Version

1.0.7 (logs says 1.2.0, but it is actually version 1.0.7)

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b606

### LoneLibs Version

v1.0.23

### FULL server log

crash logs : 
[12:42:53] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH  - git-Purpur-1858 (MC: 1.19.2) ---
[12:42:53] [Watchdog Thread/ERROR]: The server has not responded for 119 seconds! Creating thread dump
[12:42:53] [Watchdog Thread/ERROR]: ------------------------------
[12:42:53] [Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Purpur!):
[12:42:53] [Watchdog Thread/ERROR]: ------------------------------
[12:42:53] [Watchdog Thread/ERROR]: Current Thread: Server thread
[12:42:53] [Watchdog Thread/ERROR]: 	PID: 41 | Suspended: false | Native: false | State: RUNNABLE
[12:42:53] [Watchdog Thread/ERROR]: 	Stack:
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553)
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[12:42:53] [Watchdog Thread/ERROR]: 		ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.Connection.sendPacket(Connection.java:431)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.Connection.processQueue(Connection.java:548)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.Connection.flushQueue(Connection.java:504)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.Connection.send(Connection.java:399)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2257)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2243)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.nms.aH.impl.v1_19_R1.a(SourceFile:71)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.nms.aH.impl.v1_19_R1.b(SourceFile:44)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.nms.aH.aJ.a(SourceFile:60)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.nms.aH.aN.a(SourceFile:62)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.nms.aa.impl.v1_19_R1.c(SourceFile:310)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.main.v.i(SourceFile:170)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.main.i.i(SourceFile:212)
[12:42:53] [Watchdog Thread/ERROR]: 		CosmeticsCore_1.2.0.jar//dev.lone.cosmeticscore.main.A.a(SourceFile:405)
[12:42:53] [Watchdog Thread/ERROR]: 		java.base@17.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800c0a400.invokeSpecial(LambdaForm$DMH)
[12:42:53] [Watchdog Thread/ERROR]: 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000803765400.invoke(LambdaForm$MH)
[12:42:53] [Watchdog Thread/ERROR]: 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802459800.invoke_MT(LambdaForm$MH)
[12:42:53] [Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[12:42:53] [Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:42:53] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:42:53] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$12341/0x00000008033827e0.run(Unknown Source)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.TickTask.run(TickTask.java:18)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
[12:42:53] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$4457/0x000000080153a250.run(Unknown Source)
[12:42:53] [Watchdog Thread/ERROR]: 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[12:42:53] [Watchdog Thread/ERROR]: ------------------------------
[12:42:53] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---
[12:42:53] [Watchdog Thread/ERROR]: ------------------------------

### Error (optional)

```shell
[11:40:16] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CosmeticsCore v1.0.7
java.lang.IllegalArgumentException: World unloaded
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.Location.getWorld(Location.java:112) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at dev.lone.cosmeticscore.main.i.i(SourceFile:198) ~[CosmeticsCore_1.2.0.jar:?]
	at dev.lone.cosmeticscore.main.A.a(SourceFile:405) ~[CosmeticsCore_1.2.0.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:40:17] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CosmeticsCore v1.0.7
java.lang.IllegalArgumentException: World unloaded
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.Location.getWorld(Location.java:112) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at dev.lone.cosmeticscore.main.i.i(SourceFile:198) ~[CosmeticsCore_1.2.0.jar:?]
	at dev.lone.cosmeticscore.main.A.a(SourceFile:405) ~[CosmeticsCore_1.2.0.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Very strange, thanks for the report I'll check if I can reproduce the issue and let you know

**Comment by LoneDev6** [comment]
For some reason your server is triggering a PlayerMoveEvent in unloaded worlds, I have no idea why this happens on your server.
I'll try to implement a little fix for that particular case, thanks.
