### ISSUE TITLE
Cosmetics Core disabled plugin bug

### ISSUE THREAD

**Issue by xMandoU** [PluginBugs/Issues-CosmeticsCore#108]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

MandoU#0001

### What happened?

I've followed the wiki to install CosmeticsCore using items-adder but the plugin is disabled every time. I've updated the dependencies to the latest versions and have redone the installation a lot. I've asked for help from my hosting provider but was told that it could be an issue with the plugin and I should report it here. 

### Steps to reproduce the issue

Followed wiki for installation of CosmeticsCore using items adder to manage the cosmeticsCore resourcepack

### Server version

Paper 1.19.3 - Paper-392

### CosmeticsCore Version

CosmeticsCore version 1.2.0b

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b614

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
[03:58:57] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.2.0b (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "org.bukkit.Bukkit.getPluginCommand(String)" is null
    at dev.lone.cosmeticscore.main.b.<init>(SourceFile:14) ~[CosmeticsCore_1.2.0b (3).jar:?]
    at dev.lone.cosmeticscore.main.f.<init>(SourceFile:25) ~[CosmeticsCore_1.2.0b (3).jar:?]
    at dev.lone.cosmeticscore.main.c.f(SourceFile:13) ~[CosmeticsCore_1.2.0b (3).jar:?]
    at dev.lone.cosmeticscore.Main.onEnable(SourceFile:53) ~[CosmeticsCore_1.2.0b (3).jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-392]
    at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-392]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-392]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-392]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-392]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-392]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-392]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:58:57] [Server thread/INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.2.0b
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: true
```

**Comment by LoneDev6** [comment]
Post your whole server log

**Comment by xMandoU** [comment]
[latest (5).log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10976428/latest.5.log)

**Comment by LoneDev6** [comment]
Thanks!
This is caused by some other plugin which have the same cosmeticscore commands.
For example `wardrobe` or `cosmetics`.

I will fix that in the upcoming update.
