### ISSUE TITLE
bedrock player

### ISSUE THREAD

**Issue by WhiteProject1** [PluginBugs/Issues-CosmeticsCore#109]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

! Batuhan#0101

### What happened?

bedrock player constantly errors console once logged in
it would be nice if they just bring an event like bedrock ignoring the players

### Steps to reproduce the issue

...

### Server version

![image](https://user-images.githubusercontent.com/103301275/225735819-60d4a5c3-9f33-409d-8574-938a024afaf4.png)

### CosmeticsCore Version

![image](https://user-images.githubusercontent.com/103301275/225735881-05fd8a5b-d739-4034-96b7-facedfadfb32.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/103301275/225735935-36d8d445-4bbe-4c2d-9982-af291c1be335.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/103301275/225735984-2704ac1d-7f7b-494f-9c6a-c42b32aa4308.png)

### Error (optional)

```shell
[22:33:36 WARN]: java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.
canSee(org.bukkit.entity.Entity)'
[22:33:36 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.b(SourceFile:710)
[22:33:36 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.e(SourceFile:679)
[22:33:36 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.a(SourceFile:649)
[22:33:36 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.j.z(SourceFile:177)
[22:33:36 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdap
ter.call(Executors.java:539)
[22:33:36 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset
(FutureTask.java:305)
[22:33:36 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExe
cutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[22:33:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.run
Worker(ThreadPoolExecutor.java:1136)
[22:33:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Wor
ker.run(ThreadPoolExecutor.java:635)
[22:33:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:33:37 WARN]: java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.
canSee(org.bukkit.entity.Entity)'
[22:33:37 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.b(SourceFile:710)
[22:33:37 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.e(SourceFile:679)
[22:33:37 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.a(SourceFile:649)
[22:33:37 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.j.z(SourceFile:177)
[22:33:37 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdap
ter.call(Executors.java:539)
[22:33:37 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset
(FutureTask.java:305)
[22:33:37 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExe
cutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[22:33:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.run
Worker(ThreadPoolExecutor.java:1136)
[22:33:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Wor
ker.run(ThreadPoolExecutor.java:635)
[22:33:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:33:38 WARN]: java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.
canSee(org.bukkit.entity.Entity)'
[22:33:38 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.b(SourceFile:710)
[22:33:38 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.e(SourceFile:679)
[22:33:38 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.a(SourceFile:649)
[22:33:38 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.j.z(SourceFile:177)
[22:33:38 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdap
ter.call(Executors.java:539)
[22:33:38 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset
(FutureTask.java:305)
[22:33:38 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExe
cutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[22:33:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.run
Worker(ThreadPoolExecutor.java:1136)
[22:33:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Wor
ker.run(ThreadPoolExecutor.java:635)
[22:33:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:33:39 WARN]: java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.
canSee(org.bukkit.entity.Entity)'
[22:33:39 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.b(SourceFile:710)
[22:33:39 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.e(SourceFile:679)
[22:33:39 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.i.a(SourceFile:649)
[22:33:39 WARN]:        at CosmeticsCore_1.2.0b.jar//dev.lone.cosmeticscore.main
.j.z(SourceFile:177)
[22:33:39 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdap
ter.call(Executors.java:539)
[22:33:39 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset
(FutureTask.java:305)
[22:33:39 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExe
cutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[22:33:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.run
Worker(ThreadPoolExecutor.java:1136)
[22:33:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Wor
ker.run(ThreadPoolExecutor.java:635)
[22:33:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### CosmeticsCore config.yml

```shell
classic config nothing different
```

**Comment by LoneDev6** [comment]
This error has nothing to d o with bedrock players.
Seems 1.17 doesn't have an important method for players.

I'll fix that as soon as possible.

**Comment by LoneDev6** [comment]
Thanks for the patience, I'm working on it

**Comment by Lerphie** [comment]
> Thanks for the patience, I'm working on it
Hi! Do I have a similar problem?
![image](https://user-images.githubusercontent.com/66962762/231610389-320ac150-97c1-4337-9581-d1f618067e7f.png)
