### ISSUE TITLE
Failed to pass Event to CosmeticsCore

### ISSUE THREAD

**Issue by wiktormalyska** [PluginBugs/Issues-CosmeticsCore#128]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

pmalys#0585

### What happened?

Error on itemsadder reload

### Steps to reproduce the issue

1. Reload IA

### Server version

[23:14:40 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version

### CosmeticsCore Version

 CosmeticsCore version 1.2.2

### ProtocolLib Version

[23:15:21 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-636
[23:15:21 INFO]: Provides read/write access to the Minecraft protocol.
[23:15:21 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:15:34 INFO]: LoneLibs version 1.0.24
[23:15:34 INFO]: Collection of libs used by my plugins
[23:15:34 INFO]: Authors: LoneDev and others

### FULL server log

C:\Users\wikim\Desktop\MC\Server>java -Xms6G -Xmx6G -jar paper.jar --nogui
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
[23:06:52 INFO]: Building unoptimized datafixer
[23:06:53 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:06:55 INFO]: Loaded 7 recipes
[23:06:56 INFO]: Starting minecraft server version 1.19.3
[23:06:56 INFO]: Loading properties
[23:06:56 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
[23:06:56 INFO]: Server Ping Player Sample Count: 12
[23:06:56 INFO]: Using 4 threads for Netty based IO
[23:06:56 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 6 worker threads, and gen parallelism of 6 threads
[23:06:56 INFO]: Default game type: SURVIVAL
[23:06:56 INFO]: Generating keypair
[23:06:56 INFO]: Starting Minecraft server on 127.0.0.1:25565
[23:06:56 INFO]: Using default channel type
[23:06:56 INFO]: Paper: Using Java compression from Velocity.
[23:06:56 INFO]: Paper: Using Java cipher from Velocity.
[23:06:57 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.67
[23:06:57 INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.2
[23:06:57 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[23:06:57 INFO]: [MythicMobs] Loading server plugin MythicMobs v5.2.1-fd1d0777
[23:06:57 INFO]: [LumineUtils] (io.lumine.mythic.bukkit.utils.) is bound to plugin MythicMobs - io.lumine.mythic.bukkit.MythicBukkit
[23:06:57 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.0.0-SNAPSHOT-636
[23:06:58 INFO]: [LightAPI] Loading server plugin LightAPI vbukkit-5.3.0 (build SNAPSHOT)
[23:06:58 INFO]: <LightAPI>: [INFO] Preparing LightAPI...
[23:06:58 INFO]: <LightAPI>: [INFO] Preparing done!
[23:06:58 INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.24
[23:06:58 INFO]: [Essentials] Loading server plugin Essentials v2.19.7
[23:06:58 INFO]: [ModelEngine] Loading server plugin ModelEngine vR3.1.5
[23:06:58 INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.4.1-r6
[23:06:58 INFO]: [MCPets] Loading server plugin MCPets v3.0.2
[23:06:58 WARN]: [MCPets] : WorldGuard could not be found. Flags won't be available.
[23:06:58 INFO]: [LPC] Loading server plugin LPC v3.6.0
[23:06:58 INFO]: [DeluxeMenus] Loading server plugin DeluxeMenus v1.13.6-Release
[23:06:58 WARN]: [DeluxeMenus] Could not setup a NMS hook for your server version!
[23:06:58 INFO]: [CosmeticsCore] Loading server plugin CosmeticsCore v1.2.2
[23:06:58 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:06:58 INFO]: [LuckPerms] Enabling LuckPerms v5.4.67
[23:06:59 INFO]:         __
[23:06:59 INFO]:   |    |__)   LuckPerms v5.4.67
[23:06:59 INFO]:   |___ |      Running on Bukkit - Paper
[23:06:59 INFO]:
[23:06:59 INFO]: [LuckPerms] Loading configuration...
[23:06:59 INFO]: [LuckPerms] Loading storage provider... [H2]
[23:07:00 INFO]: [LuckPerms] Loading internal permission managers...
[23:07:00 INFO]: [LuckPerms] Performing initial data load...
[23:07:00 INFO]: [LuckPerms] Successfully enabled. (took 1722ms)
[23:07:00 INFO]: [Vault] Enabling Vault v1.7.3-b131
[23:07:00 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[23:07:00 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[23:07:00 INFO]: [Vault] Enabled Version 1.7.3-b131
[23:07:00 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[23:07:00 INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-636
[23:07:00 INFO]: [LoneLibs] Enabling LoneLibs v1.0.24
[23:07:00 INFO]: Preparing level "world"
[23:07:01 INFO]: Preparing start region for dimension minecraft:overworld
[23:07:01 INFO]: Time elapsed: 246 ms
[23:07:01 INFO]: Preparing start region for dimension minecraft:the_nether
[23:07:01 INFO]: Time elapsed: 23 ms
[23:07:01 INFO]: Preparing start region for dimension minecraft:the_end
[23:07:01 INFO]: Time elapsed: 17 ms
[23:07:01 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.2
[23:07:02 INFO]: [PlaceholderAPI] Fetching available expansion information...
[23:07:02 INFO]: [MythicMobs] Enabling MythicMobs v5.2.1-fd1d0777
[23:07:03 INFO]: [MythicMobs] Loading MythicMobs for Paper (MC: 1.19.3)...
[23:07:03 INFO]: [MythicMobs] The server is running PaperSpigot; enabled PaperSpigot exclusive functionality
[23:07:03 INFO]: [MythicMobs] MythicMobs PlaceholderAPI Support has been enabled!
[23:07:03 INFO]: [MythicMobs] MythicMobs ProtocolLib Support has been enabled!
[23:07:03 INFO]: [MythicMobs] MythicMobs Vault Support has been enabled!
[23:07:03 INFO]: [MythicMobs] Base directory C:\Users\wikim\Desktop\MC\Server\plugins\MythicMobs\SavedData
[23:07:03 INFO]: [MythicMobs] Module directory C:\Users\wikim\Desktop\MC\Server\plugins\MythicMobs\SavedData\worlds
[23:07:04 INFO]: [MythicMobs] LOADED
[23:07:04 INFO]: [MythicMobs] Loading Packs...
[23:07:04 INFO]: [MythicMobs] Loading Items...
[23:07:04 INFO]: [MythicMobs] Loading Item Groups...
[23:07:04 INFO]: [MythicMobs] Loading Skills...
[23:07:04 INFO]: [MythicMobs] Loading Drop Tables...
[23:07:04 INFO]: [MythicMobs] Loading Random Spawns...
[23:07:04 INFO]: [MythicMobs] Loading Spawn Blocks...
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 16 mobs.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 3 vanilla mob overrides.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 46 skills.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 0 random spawns.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 3 mythic items.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 2 drop tables.
[23:07:05 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[23:07:05 INFO]: [MythicMobs] MythicMobs configuration file loaded successfully.
[23:07:05 INFO]: [MythicMobs] Started up bStats Metrics
[23:07:05 INFO]: [MythicMobs] ✓ MythicMobs Premium v5.2.1 ( build fd1d0777 ) has been successfully loaded!
[23:07:05 INFO]: [LightAPI] Enabling LightAPI vbukkit-5.3.0 (build SNAPSHOT)
[23:07:05 INFO]: <LightAPI>: [INFO] Initializing LightAPI...
[23:07:05 INFO]: <LightAPI>: [INFO] Force legacy is enabled
[23:07:05 INFO]: <LightAPI>: [INFO] Compatibility mode is enabled
[23:07:05 INFO]: <LightAPI>: [INFO] Metrics is enabled!
[23:07:05 INFO]: <LightAPI>: [INFO] LightAPI initialized!
[23:07:05 INFO]: [Essentials] Enabling Essentials v2.19.7
[23:07:05 ERROR]: [Essentials] You are running an unsupported server version!
[23:07:05 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[23:07:05 INFO]: [Essentials] No kits found to migrate.
[23:07:05 INFO]: [Essentials] Loaded 36926 items from items.json.
[23:07:05 INFO]: [Essentials] Using locale en_GB
[23:07:05 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[23:07:05 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[23:07:05 INFO]: [Vault] [Economy] Essentials Economy hooked.
[23:07:05 INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[23:07:05 INFO]: [ModelEngine] Enabling ModelEngine vR3.1.5
[23:07:05 INFO]: [MythicMobs] Model Engine Compatibility Loaded.
[23:07:05 INFO]: [ModelEngine] [S] Compatibility applied: MythicMobs
[23:07:05 INFO]: [ItemsAdder] Enabling ItemsAdder v3.4.1-r6
[23:07:05 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R2! Trying to find NMS support
[23:07:05 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R2' loaded!
[23:07:05 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[23:07:06 INFO]: [ItemsAdder]
  ___  ___        __        __   __   ___  __      ItemsAdder 3.4.1-r6
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.24
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-448 (MC: 1.19.3)

[23:07:06 INFO]: [ItemsAdder] [Host] Starting self-host webserver on port: 8163
[23:07:06 WARN]: [ItemsAdder] "ItemsAdder v3.4.1-r6" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.fE.a(org.bukkit.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev].
[23:07:06 INFO]: [MCPets] Enabling MCPets v3.0.2
[23:07:06 INFO]: [MCPets] : Language file reloaded.
[23:07:06 INFO]: [MCPets] : Blacklist file reloaded.
[23:07:06 INFO]: Loading pets...
[23:07:06 INFO]: [MCPets] : 0 pets registered successfully !
[23:07:06 INFO]: [MCPets] : 0 categories registered successfully !
[23:07:06 ERROR]: [MCPets] Could not reach SQL database. Please configure your database parameters.
[23:07:06 ERROR]: [MCPets] [Database] Can't initialize MySQL.
[23:07:06 ERROR]: [MCPets] [Database] Will be using YAML support instead.
[23:07:06 INFO]: -=-=-=-= MCPets loaded =-=-=-=-
[23:07:06 INFO]:       Plugin made by Nocsy
[23:07:06 INFO]: -=-=-=-= -=-=-=-=-=-=- =-=-=-=-
[23:07:06 INFO]: -=- Launching Flags -=-
[23:07:06 INFO]: 0 flags launched.
[23:07:06 INFO]: [LPC] Enabling LPC v3.6.0
[23:07:06 INFO]: [DeluxeMenus] Enabling DeluxeMenus v1.13.6-Release
[23:07:06 INFO]: [DeluxeMenus] Successfully hooked into PlaceholderAPI!
[23:07:06 INFO]: [DeluxeMenus] 5 GUI menus loaded!
[23:07:06 INFO]: [DeluxeMenus] You are running the latest version of DeluxeMenus!
[23:07:06 INFO]: [DeluxeMenus] Successfully hooked into Vault!
[23:07:06 INFO]: [PlaceholderAPI] Successfully registered expansion: deluxemenus [1.13.6-Release]
[23:07:06 INFO]: [CosmeticsCore] Enabling CosmeticsCore v1.2.2
[23:07:07 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[23:07:07 INFO]: Running delayed init tasks
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [Essentials] Fetching version information...
[23:07:07 INFO]: [ModelEngine] [A] [Importing models]
[23:07:07 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing black_lawnmower.bbmodel.
[23:07:07 INFO]: [CosmeticsCore] [License] Store product licensed to: pmalys (11416)
[23:07:07 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[23:07:07 INFO]: [Vault] Checking for Updates ...
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing blue_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing cube_pets.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing green_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing orange_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing pink_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing red_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing white_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Importing yellow_lawnmower.bbmodel.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] [Generating assets]
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating black_lawnmower.
[23:07:07 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[23:07:07 INFO]: [ItemsAdder] [License] Spigot product licensed to: pmalysYT (621204)
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating blue_lawnmower.
[23:07:07 INFO]: [Vault] No new version available
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating cube_pets.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating green_lawnmower.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating orange_lawnmower.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating pink_lawnmower.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating red_lawnmower.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating white_lawnmower.
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Generating yellow_lawnmower.
[23:07:07 INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.3]
[23:07:07 INFO]: 1 placeholder hook(s) registered! 1 placeholder hook(s) have an update available.
[23:07:07 INFO]: [PlaceholderAPI] An update for PlaceholderAPI (v2.11.3) is available at:
[23:07:07 INFO]: [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
[23:07:07 INFO]: Done (11.379s)! For help, type "help"
[23:07:07 INFO]: Timings Reset
[23:07:07 INFO]: [ModelEngine] [A]
[23:07:07 INFO]: [ModelEngine] [A] Resource pack zipped.
[23:07:07 INFO]: [ItemsAdder] Loaded 10 items
[23:07:07 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[23:07:07 INFO]: [ItemsAdder] Used 52/750 REAL_NOTE block IDs
[23:07:07 INFO]: [ItemsAdder] Used 21/63 REAL_TRANSPARENT block IDs
[23:07:07 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[23:07:07 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[23:07:07 INFO]: [ItemsAdder] Used 67/6608 font_images
[23:07:07 INFO]: [ItemsAdder] [Init] Loaded 2 categories
[23:07:07 INFO]: [ItemsAdder] [Init] Loaded successfully.
[23:07:07 INFO]: [ItemsAdder] [Pack] Checking resourcepack url...
[23:07:07 INFO]: [ItemsAdder] [Pack] Resourcepack URL (self-host): http://127.0.0.1:8163/generated.zip
[23:07:07 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[23:07:07 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[23:07:07 ERROR]: Could not pass event ItemsAdderLoadDataEvent to CosmeticsCore v1.2.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because "<local2>" is null
        at dev.lone.cosmeticscore.main.P.a(SourceFile:28) ~[CosmeticsCore_1.2.2.jar:?]
        at dev.lone.cosmeticscore.main.j.a(SourceFile:242) ~[CosmeticsCore_1.2.2.jar:?]
        at dev.lone.cosmeticscore.main.H.a(SourceFile:58) ~[CosmeticsCore_1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at ia.m.kR.a(SourceFile:68) ~[ItemsAdder_3.4.1-r6.jar:?]
        at ia.m.I.c(SourceFile:2425) ~[ItemsAdder_3.4.1-r6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[23:07:07 INFO]: [Mythic] Reloading plugin...
[23:07:07 INFO]: [MythicMobs] Mythic beginning reload procedure...
[23:07:07 INFO]: [MythicMobs] Loading Packs...
[23:07:07 INFO]: [MythicMobs] Loading Items...
[23:07:07 INFO]: [MythicMobs] Loading Item Groups...
[23:07:07 INFO]: [MythicMobs] Loading Skills...
[23:07:07 INFO]: [MythicMobs] Loading Drop Tables...
[23:07:07 INFO]: [MythicMobs] Loading Random Spawns...
[23:07:07 INFO]: [MythicMobs] Loading Spawn Blocks...
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 16 mobs.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 3 vanilla mob overrides.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 46 skills.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 0 random spawns.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 3 mythic items.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 2 drop tables.
[23:07:07 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[23:07:07 INFO]: [Mythic] Mythic has finished reloading!
[23:07:07 INFO]: [MythicMobs] Mythic has finished reloading!
> version
[23:14:40 INFO]: Checking version, please wait...
[23:14:40 INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
> version cosmeticscore
[23:15:02 INFO]: CosmeticsCore version 1.2.2
> version protocolib
[23:15:18 INFO]: This server is not running any plugin by that name.
[23:15:18 INFO]: Use /plugins to get a list of plugins.
> version protocollib
[23:15:21 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-636
[23:15:21 INFO]: Provides read/write access to the Minecraft protocol.
[23:15:21 INFO]: Authors: dmulloy2 and comphenix
> version lonelibs
[23:15:34 INFO]: LoneLibs version 1.0.24
[23:15:34 INFO]: Collection of libs used by my plugins
[23:15:34 INFO]: Authors: LoneDev and others
>

### Error (optional)

```shell
[23:07:07 ERROR]: Could not pass event ItemsAdderLoadDataEvent to CosmeticsCore v1.2.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because "<local2>" is null
        at dev.lone.cosmeticscore.main.P.a(SourceFile:28) ~[CosmeticsCore_1.2.2.jar:?]
        at dev.lone.cosmeticscore.main.j.a(SourceFile:242) ~[CosmeticsCore_1.2.2.jar:?]
        at dev.lone.cosmeticscore.main.H.a(SourceFile:58) ~[CosmeticsCore_1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at ia.m.kR.a(SourceFile:68) ~[ItemsAdder_3.4.1-r6.jar:?]
        at ia.m.I.c(SourceFile:2425) ~[ItemsAdder_3.4.1-r6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### CosmeticsCore config.yml

```shell
lspd_vest:
  display_name: '&b&lLSPD Vest'
  type: BODY_ITEM
  model:
    gui: bettermobs:lspd_vest_model
    normal: bettermobs:lspd_vest_model
    self: bettermobs:empty_model
  dye:
    enabled: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: bettermobs
items:
  lspd_vest_model:
    display_name: '&b&lLSPD Vest'
    resource:
      generate: false
      model_path: 'vests/lspd_vest'
      material: PAPER
    all_actions_permission: bettermobs.models.lspd_vest
    
  empty_model:
    display_name: '&b&lEmpty Model'
    resource:
      generate: false
      model_path: 'vests/empty'
      material: PAPER
    all_actions_permission: bettermobs.models.empty
```

**Comment by wiktormalyska** [comment]
no problem, i wish you rested well 👍🏻

**Comment by LoneDev6** [comment]
Your configuration is malformed.
It's missing the `cosmetics` tag.

Wrong:
```yml
lspd_vest:
  display_name: '&b&lLSPD Vest'
  type: BODY_ITEM
  model:
    gui: bettermobs:lspd_vest_model
    normal: bettermobs:lspd_vest_model
    self: bettermobs:empty_model
  dye:
    enabled: false
```

good:
```yml
cosmetics:
  lspd_vest:
    display_name: '&b&lLSPD Vest'
    type: BODY_ITEM
    model:
      gui: bettermobs:lspd_vest_model
      normal: bettermobs:lspd_vest_model
      self: bettermobs:empty_model
    dye:
      enabled: false
```
