### ISSUE TITLE
Not support Java 11

### ISSUE THREAD

**Issue by GsTio86** [PluginBugs/Issues-CosmeticsCore#134]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

GT86#1000

### What happened?

Like CinematicStudio in the past, Java 11 is not supported

### Steps to reproduce the issue

Use Java11 and Arclight-1.16.5-1.0.25 run this plugin

### Server version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/74390539/42c2dec9-350c-4372-be56-e8cee15b2d94)

### CosmeticsCore Version

1.2.2c

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/74390539/c5230139-75c2-4646-8738-b7e6544da5ab)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/74390539/59da7cb6-5139-455f-bd7e-04a78e40bfba)

### Error (optional)

```shell
[18May2023 17:40:37.454] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/CosmeticsCore_1.2.2c.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/lone/cosmeticscore/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:149) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:332) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:381) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at net.minecraft.server.dedicated.DedicatedServer.handler$bbj000$arclight$loadPlugins(DedicatedServerMixin.java:637) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1878) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: dev/lone/cosmeticscore/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:644) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:104) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoaderMixin.java:67) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:145) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-775e7cb3]
	... 8 more
```

**Comment by LoneDev6** [comment]
Install Java 15 or 16, it will work just fine
