### ISSUE TITLE
set door-area-locations, command throwing problems.

### ISSUE THREAD

**Issue by EssosMc** [PluginBugs/Issues-CosmeticsCore#140]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Upon using the command **/cosmeticsconfig config set door-area-locations**, the chat says to interact with the blocks to select your area. When doing that the blocks break and don't get selected.

### Steps to reproduce the issue

1. Load up a 1.19.2 Server
2. Use the /cosmeticsconfig config set door-area-locations command
3. Try to select the blocks

### Server version

This server is running Arclight version arclight-1.19.2-1.0.2-4a870b30 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version 1.2.2d

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/11594261/latest.log)

Its quite a long log, error is at the bottom

### Error (optional)

```shell
[14:04:47] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CosmeticsCore v1.2.2d

com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0

at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]

at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]

at dev.lone.cosmeticscore.nms.aK.aP.a(SourceFile:44) ~[CosmeticsCore_1.2.2d.jar:?]

at dev.lone.cosmeticscore.nms.aK.aP.a(SourceFile:27) ~[CosmeticsCore_1.2.2d.jar:?]

at dev.lone.cosmeticscore.main.d.a(SourceFile:176) ~[CosmeticsCore_1.2.2d.jar:?]

at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.2.jar:git-Paper-307]

at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.19.2.jar:git-Paper-307]

at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[paper-1.19.2.jar:git-Paper-307]

at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:198) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1883) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]

at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]

at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -1757.0811095820213
      y: 118.62000000476837
      z: 2853.745003292498
      yaw: 62.956787
      pitch: 43.091084
  mannequin:
    location:
      world: world
      x: -1754.461446404268
      y: 117.0
      z: 2849.6114992693792
      yaw: 62.956787
      pitch: 43.091084
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: world
      x: -1770.3167005476262
      y: 116.0
      z: 2858.272956205483
      yaw: 62.956787
      pitch: 43.091084
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

**Comment by LoneDev6** [comment]
You're using arclight.
It probably has some strange stuff going on in the [ClientboundCustomPayloadPacket ](https://nms.screamingsandals.org/1.19.2/net/minecraft/network/protocol/game/ClientboundCustomPayloadPacket.html)packet.
The plugin can't find the `ByteBuf` field, probably arclight is removing it or changed its type.

Try the plugin on Spigot or Paper 1.19.2 (or better 1.19.4). I'm sure it works fine.

I'd ask arclight developers for more info about that.
