### ISSUE TITLE
Random java.util.ConcurrentModificationException when there are players online

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-CosmeticsCore#152]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Nailm#9364

### What happened?

Random ConcurrentModificationException occurs on the console if there are players online (literally it's just me, one player).

I don't put any cosmetics on btw, tho there are cosmetics in the database.

Just let me know if you need more information ;))

### Steps to reproduce the issue

Just have some players online and I would get this error ...

### Server version

Current: git-Purpur-2017 (MC: 1.20.1)*
Previous: git-Purpur-2016 (MC: 1.20.1)
* You are 18 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### CosmeticsCore Version

CosmeticsCore version 1.2.2f

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

https://mclo.gs/YH4KSxH

### Error (optional)

```shell
[03:30:32 WARN]: java.util.ConcurrentModificationException                                                                                                                  
[03:30:32 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)                                                                    
[03:30:32 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)                                                                                       
[03:30:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getPlayers(CraftWorld.java:1229)                                                                      
[03:30:32 WARN]:        at CosmeticsCore_1.2.2f.jar//dev.lone.cosmeticscore.main.j.z(SourceFile:111)                                                                        
[03:30:32 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)                                                                
[03:30:32 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[03:30:32 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)                         
[03:30:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:30:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:30:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)                                                                                                  
[03:36:32 WARN]: java.util.ConcurrentModificationException                                                                                                                  
[03:36:32 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[03:36:32 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)                                                                                       
[03:36:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getPlayers(CraftWorld.java:1229)
[03:36:32 WARN]:        at CosmeticsCore_1.2.2f.jar//dev.lone.cosmeticscore.main.j.z(SourceFile:111)
[03:36:32 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[03:36:32 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[03:36:32 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)                         
[03:36:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:36:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:36:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)                                                                                                  
[03:39:44 INFO]: [ExcellentShop] Auto-save: Saved 1 online users | 0 offline users.                                                                                         
[03:40:39 INFO]: [ExcellentCrates] Auto-save: Saved 1 online users | 0 offline users.                                                                                       
[03:57:38 INFO]: Nailm lost connection: Disconnected
```

### CosmeticsCore config.yml

```shell
lang: zh_cn
extract_default_assets: false
cosmetics:
  max_equippable:
    body: 1
    balloon: 1
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: false
      min: 2
    fade_effect: true
    location:
      world: city
      x: 49.5
      y: 93.62000000476837
      z: -525.5
      yaw: 90.0
      pitch: 0.0
  mannequin:
    location:
      world: city
      x: 45.5
      y: 92.0
      z: -525.5
      yaw: -90.0
      pitch: 0.0
  teleport_area:
    enter:
      world: city
      pos1:
        x: 53.0
        y: 94.0
        z: -525.0
      pos2:
        x: 53.0
        y: 92.0
        z: -527.0
    exit_location:
      world: city
      x: 56.5
      y: 92.0
      z: -525.5
      yaw: 90.0
      pitch: 0.0
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 255,102,102
        owned: 56,67,100
        wearing: 255,255,255
        wearing_preview: 255,204,204
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
save:
  # Use only one at a time
  file:
    enabled: false
  mysql:
    enabled: true
    url: hidden
    username: hidden
    password: ''
    table: cosmeticscore_saved
debug: false
send_creative_hidden_hat_message: true
```

**Comment by LoneDev6** [comment]
Will be fixed, thanks!

https://bukkit.org/threads/java-util-concurrentmodificationexception-error.92020/#post-1408959
> The main issue is that getPlayers() is enumerating [entityList](https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/net/minecraft/server/World.java#L31) from a different thread than the main thread, which will randomly crash with a ConcurrentModificationException.
> 
> But there is a simple solution - use [getServer().getOnlinePlayers()](https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/org/bukkit/craftbukkit/CraftServer.java#L301) instead. It's actually [thread safe](https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/net/minecraft/server/ServerConfigurationManagerAbstract.java#L34).
