### ISSUE TITLE
java compatibility issue

### ISSUE THREAD

**Issue by mlicorne12** [PluginBugs/Issues-CosmeticsCore#160]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

licorne#1985

### What happened?

![java](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/67154310/899eedaf-b3b2-4c1b-acce-c0ed2c63d545)
hi
I have a compatibility issue with Java.
I use java 11 but I cannot update it for technical reasons.
what a can do?

### Steps to reproduce the issue

when I launch the server I have a console error saying that java is obsessed

### Server version

This server is running Arclight version arclight-1.16.5-1.0.24-551ec3ff (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore 1.2.2f
CosmeticsCore 1.0.5

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.25

### Error (optional)

```shell
Could not load 'plugins/CosmeticsCore_1.0.5.jar' in folder 'plugins'
Console23:49:18
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/lone/cosmeticscore/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:149) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:381) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
at net.minecraft.server.dedicated.DedicatedServer.handler$bah000$arclight$loadPlugins(DedicatedServerMixin.java:637) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1879) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:829) [?:?] {}
Caused by: java.lang.UnsupportedClassVersionError: dev/lone/cosmeticscore/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?] {}
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?] {}
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoaderMixin.java:644) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:104) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
at java.lang.Class.forName0(Native Method) ~[?:?] {}
at java.lang.Class.forName(Class.java:398) ~[?:?] {}
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoaderMixin.java:67) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:145) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
... 8 more
```

### CosmeticsCore config.yml

```shell
i can't
```

**Comment by LoneDev6** [comment]
Why not updating to Java 16?
There is no reason to stay on Java 11.

**Comment by mlicorne12** [comment]
we are forced to stay in java 11 because our server is on pixelmon 1.16.5 9.1.7

**Comment by LoneDev6** [comment]
Java 16 has some new good features I use and downgrading to Java 11 would require me a rewrite of some CosmeticsCore parts which I'd avoid to do as it can introduce issues and bugs.

**Comment by LoneDev6** [comment]
Pixelmon should work just fine on Java 16, I see no reason why.
Recent Java versions have backwards compatibility.

**Comment by mlicorne12** [comment]
actually pixelmon 1.16.5 support only  jave 8 and 11. it's pixelmon 1.20.1 who's supports java 17 :(

**Comment by LoneDev6** [comment]
I don't think I can downgrade for the reasons I explained before, it would mean that I have to cut off some features and I'd prefer not to.
Why not asking Pixelmon their reason why they cannot update to Java 16? I'm not aware of any incompatibility.

**Comment by mlicorne12** [comment]
would it be possible to be refound
because for me I thought that cosmestic core was compatible in java 11 because I bought itemadders and it did not have any problems with compatibility. 

for pixelmon, they've sayed that the mod will never be comp with java 16. only between java 8 and 11.

**Comment by mlicorne12** [comment]
yes 
thank you
