### ISSUE TITLE
If you enter and leave the dressing room and then move to another world, an error appears.

### ISSUE THREAD

**Issue by noveaya** [PluginBugs/Issues-CosmeticsCore#161]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

hyun_2_

### What happened?

If you enter and leave the dressing room and then move to another world, an error appears.

### Steps to reproduce the issue

https://youtu.be/kA-Lbu_riv4

### Server version

mohist-1.20.1-437-server

### CosmeticsCore Version

CosmeticsCore_1.2.2f

### ProtocolLib Version

ProtocolLib v5.1.0-SNAPSHOT-654

### LoneLibs Version

 1.0.25

### FULL server log

[16:54:21 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world and lobby
[16:54:21 WARN]:        at TRANSFORMER/forge@47.1.76/org.bukkit.Location.distanceSquared(Location.java:501)
[16:54:21 WARN]:        at com.ticxo.modelengine.api.nms.entity.impl.ManualRangeManager.updatePlayer(ManualRangeManager.java:37)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.v.U(SourceFile:276)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.v.g(SourceFile:194)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.i.g(SourceFile:141)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.j.A(SourceFile:74)
[16:54:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:54:21 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[16:54:21 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[16:54:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:54:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:54:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Error (optional)

```shell
[16:54:21 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world and lobby
[16:54:21 WARN]:        at TRANSFORMER/forge@47.1.76/org.bukkit.Location.distanceSquared(Location.java:501)
[16:54:21 WARN]:        at com.ticxo.modelengine.api.nms.entity.impl.ManualRangeManager.updatePlayer(ManualRangeManager.java:37)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.v.U(SourceFile:276)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.v.g(SourceFile:194)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.i.g(SourceFile:141)
[16:54:21 WARN]:        at dev.lone.cosmeticscore.main.j.A(SourceFile:74)
[16:54:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:54:21 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[16:54:21 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[16:54:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:54:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:54:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/kA-Lbu_riv4

**Comment by LoneDev6** [comment]
This is a bug of ModelEngine since it's trying to measure distance from two worlds, I cannot fix its code, contact its developer.
