### ISSUE TITLE
normal_2 wrong offset in wardrobe

### ISSUE THREAD

**Issue by WindUnwaken** [PluginBugs/Issues-CosmeticsCore#184]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

plugin seems not have normal_2 functiong

### Steps to reproduce the issue

1. check version of Cosmeticscore
2. use default file and remove normal
3. do reload
4. plugin give error

### Server version

git paper-291

### CosmeticsCore Version

1.2.3-r3

### ProtocolLib Version

protocolib 5.1.1-669

### LoneLibs Version

1.0.27

### FULL server log

1.0.27

### Error (optional)

```shell
[15:53:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cosmeticscore:cosmeticsconfig' in plugin CosmeticsCore v1.2.3-r3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-291]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-291]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: 'normal' model not set.
        at dev.lone.cosmeticscore.main.X.a(SourceFile:86) ~[CosmeticsCore_1.2.3-r3.jar:?]
        at dev.lone.cosmeticscore.main.j.a(SourceFile:250) ~[CosmeticsCore_1.2.3-r3.jar:?]
        at dev.lone.cosmeticscore.main.j.a(SourceFile:234) ~[CosmeticsCore_1.2.3-r3.jar:?]
        at dev.lone.cosmeticscore.main.d.a(SourceFile:54) ~[CosmeticsCore_1.2.3-r3.jar:?]
        at dev.lone.cosmeticscore.main.d.a(SourceFile:40) ~[CosmeticsCore_1.2.3-r3.jar:?]
        at dev.lone.cosmeticscore.main.b.onCommand(SourceFile:26) ~[CosmeticsCore_1.2.3-r3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

### CosmeticsCore config.yml

```shell
squirrel_tail:
    enabled: true
    display_name: "Squirrel Tail"
    type: BODY_ITEM
    model:
      gui: potion:400008
      normal: potion:400008
      normal_2: potion:410008
      self_2: potion:410009
    dye:
      enabled: false
```

### Problematic items yml configuration file (optional)

```shell
squirrel_tail:
    enabled: true
    display_name: "Squirrel Tail"
    type: BODY_ITEM
    model:
      gui: potion:400008 ########remove "normal", try to test if "normal_2" is ready
      normal_2: potion:410008
      self_2: potion:410009
    dye:
      enabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/z-gmw1DGD0k

**Comment by LoneDev6** [comment]
If your server allows 1.20.2 and lower and also 1.20.2 and greater to join you have to use both model `normal` and `normal_2`.
If your server is only on > 1.20.2  or < 1.20.2 you have to use just `normal` model.

> Normal model
A normal model is the model which is shown to every player but the local player (yourself).
This model is used only on Minecraft 1.20.1 and lower.
>
> Normal model 2
This normal model is the model which is shown to every player but the local player (yourself).
This model is used only on Minecraft 1.20.2 and greater.

Please let me know.

**Comment by WindUnwaken** [comment]
https://youtu.be/eWMg5TLUKYQ

**Comment by WindUnwaken** [comment]
My server is only run on 1.20.2 and also client.
You can see video that cosmetics height is different from outside.

**Comment by WindUnwaken** [comment]
It doesn't work.

**Comment by LoneDev6** [comment]
I will make another test but this is the default pack which was used to test the plugin before release... strange.

**Comment by WindUnwaken** [comment]
blockbench plugin for 1.20.2 is perfect, only problem is in wardobe (cosmetics preview room)

**Comment by WindUnwaken** [comment]
![擷取](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/19383943/872fda08-ad1c-462c-bd6e-054497b90d4e)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/19383943/1e27bae2-f5b4-4a78-94d8-3ee11d8de28b)

**Comment by WindUnwaken** [comment]
> I will make another test but this is the default pack which was used to test the plugin before release... strange.

I think that's not resourcepack issue, even resourcepack json is wrong,  height of tail should as same as other one

**Comment by LoneDev6** [comment]
With the last zip I sent you I cannot reproduce the issue outside the wardrobe, shown in your Youtube video.

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/04817a91-cc39-454b-9ad8-813270f83b20)

However I can trigger the wardrobe issue.
I will fix it in the upcoming update, thanks!

These are the debug images I use to highlight the different models.

[body.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/13449033/body.zip)


![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/97538e93-656b-465f-868f-01c5135ff30a)

## Fixed:

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/516d442c-3b87-474e-982f-f1b314517b4a)


## Notes:

You can use only `normal` and `self` models in the yml configuration if your server is on 1.20.2 ONLY and 1.20.1 (and lower) cannot join.
No need to use `normal_2` and `self_2`.
But in this case you would have to swap the `normal` with `normal_2` model and also `self` with `self_2`, because my packs are meant to be working on every setup.
