### ISSUE TITLE
cosmeticscore make modelengine overload

### ISSUE THREAD

**Issue by keujakga** [PluginBugs/Issues-CosmeticsCore#223]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

minho4979

### What happened?

cosmeticscore make modelengine overload.
that make server tps very low

### Steps to reproduce the issue

1, Go to server start.bat
2. Click on start.bat
3. use command /tps and /timings report
4. can see modelengine make lag

### Server version

Paper version git-Paper-496 (MC: 1.20.4)
(Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1ver/1.20.4)

### CosmeticsCore Version

CosmeticsCore version 1.2.3d

### ProtocolLib Version

ProtocolLib version 5.2.1-SNAPSHOT-689

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/15293735/latest.log)

### Error (optional)

```shell
[01:00:00] [Server thread/WARN]: [CosmeticsCore] Task #3115845 for CosmeticsCore v1.2.3d generated an exception
java.lang.IndexOutOfBoundsException: readerIndex(13) + length(1) exceeds writerIndex(13): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 13, widx: 13, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.VarInt.read(VarInt.java:43) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.network.FriendlyByteBuf.readVarInt(FriendlyByteBuf.java:576) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.readIntIdList(FriendlyByteBuf.java:246) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundRemoveEntitiesPacket.<init>(ClientboundRemoveEntitiesPacket.java:20) ~[?:?]
	at com.ticxo.modelengine.v1_20_R3.parser.model.DisplayParser.remove(DisplayParser.java:209) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.v1_20_R3.parser.model.DisplayParser.destroy(DisplayParser.java:83) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.v1_20_R3.parser.model.DisplayParser.destroy(DisplayParser.java:28) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.render.DisplayRendererImpl.destroy(DisplayRendererImpl.java:197) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.ActiveModelImpl.destroy(ActiveModelImpl.java:167) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.ModeledEntityImpl.lambda$destroy$0(ModeledEntityImpl.java:122) ~[ModelEngine-4.0.5.jar:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at com.ticxo.modelengine.core.model.ModeledEntityImpl.destroy(ModeledEntityImpl.java:122) ~[ModelEngine-4.0.5.jar:?]
	at dev.lone.cosmeticscore.main.G.ab(SourceFile:68) ~[CosmeticsCore_1.2.3d.jar:?]
	at dev.lone.cosmeticscore.main.v.y(SourceFile:313) ~[CosmeticsCore_1.2.3d.jar:?]
	at dev.lone.cosmeticscore.main.i.q(SourceFile:583) ~[CosmeticsCore_1.2.3d.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]




next error
[02:39:15] [pool-74-thread-1/WARN]: java.lang.NullPointerException: Cannot invoke "dev.lone.cosmeticscore.nms.aE.aE.a(org.bukkit.util.Vector)" because "this.b" is null
[02:39:15] [pool-74-thread-1/WARN]: 	at CosmeticsCore_1.2.3d.jar//dev.lone.cosmeticscore.main.v.g(SourceFile:219)
[02:39:15] [pool-74-thread-1/WARN]: 	at CosmeticsCore_1.2.3d.jar//dev.lone.cosmeticscore.main.i.g(SourceFile:159)
[02:39:15] [pool-74-thread-1/WARN]: 	at CosmeticsCore_1.2.3d.jar//dev.lone.cosmeticscore.main.j.C(SourceFile:77)
[02:39:15] [pool-74-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[02:39:15] [pool-74-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[02:39:15] [pool-74-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[02:39:15] [pool-74-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:39:15] [pool-74-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:39:15] [pool-74-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

### CosmeticsCore config.yml

```shell
lang: ko
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
  hide_during_combat:
    enabled: false
    combat_duration_ticks: 10000
  fix_invisible_nametag: true
  hide_in_vanish: true
  worlds:
  - '*'
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    use_invisibility_potion: false
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: 218.190516957956
      y: 132.1779352487657
      z: -1150.8740207734745
      yaw: -120.70703
      pitch: 29.69952
  mannequin:
    location:
      world: world
      x: 222.41738257480372
      y: 128.0
      z: -1153.5623719672342
      yaw: 89.646484
      pitch: -4.2002077
  teleport_area:
    enter:
      world: world
      pos1:
        x: 216.0
        y: 128.0
        z: -1156.0
      pos2:
        x: 216.0
        y: 130.0
        z: -1152.0
    exit_location:
      world: world
      x: 207.36090700565902
      y: 130.0
      z: -1157.5538268429375
      yaw: -92.059296
      pitch: 3.5989084
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/169536107/e369e7ac-80cd-46b2-bfb6-cdb502d4c4ce)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/169536107/117879fe-5678-4c7b-be7b-1e71b4504458)

**Comment by keujakga** [comment]
Hello, @LoneDev6 is this bug being fixed?

**Comment by LoneDev6** [comment]
This sounds like a ModelEngine issue
