### ISSUE TITLE
CosmeticsCore error

### ISSUE THREAD

**Issue by dafsdfasde** [PluginBugs/Issues-CosmeticsCore#230]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

load error

### Steps to reproduce the issue

This problem occurs when you update itemsadder, LoneLibs, and ProtocolLib to the latest version.

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-2062 (MC: 1.20.1)

### CosmeticsCore Version

CosmeticsCore version 1.2.3d

### ProtocolLib Version

[22:17:34 INFO]: ProtocolLib version 5.2.1-SNAPSHOT-689
[22:17:34 INFO]: Provides read/write access to the Minecraft protocol.
[22:17:34 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[22:17:25 INFO]: LoneLibs version 1.0.54
[22:17:25 INFO]: Collection of libs used by my plugins
[22:17:25 INFO]: Authors: LoneDev and others

### FULL server log

[22:11:36 ERROR]: Error occurred while enabling CosmeticsCore v1.2.3d (Is it up to date?)
java.lang.NoSuchMethodError: 'void dev.lone.LoneLibs.nbt.nbtapi.NBTItem.saveMetaChanges()'
        at dev.lone.cosmeticscore.main.aC.a(SourceFile:26) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.main.as.a(SourceFile:46) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.main.aq.a(SourceFile:48) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.b.b(SourceFile:109) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:59) ~[CosmeticsCore_1.2.3d.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 2
    balloon: 1
  hide_during_combat:
    enabled: false
    combat_duration_ticks: 10000
  fix_invisible_nametag: true
  hide_in_vanish: true
  worlds:
  - '*'
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    use_invisibility_potion: false
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
```

**Comment by Bujaejung** [comment]
I also downloaded itemsadder 3.6.4 and the latest protocol libs and lonelibs, but Cosmetic Core does not work.

**Comment by inrhor** [comment]
CosmeticCore just support LoneLibs-1.045, But it does not support the latest ia and lib. This is a stupid thing.

**Comment by WolfLiSteel** [comment]
Mine is like this with 1.20.4

[09:31:45 ERROR]: Error occurred while enabling CosmeticsCore v1.2.3d (Is it up to date?)
java.lang.NoSuchMethodError: 'void dev.lone.LoneLibs.nbt.nbtapi.NBTItem.saveMetaChanges()'
        at dev.lone.cosmeticscore.main.aC.a(SourceFile:26) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.main.as.a(SourceFile:46) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.main.aq.a(SourceFile:48) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.b.b(SourceFile:109) ~[CosmeticsCore_1.2.3d.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:59) ~[CosmeticsCore_1.2.3d.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by DxrkCat** [comment]
@LoneDev6 When will you fix this problem?

**Comment by inrhor** [comment]
> @LoneDev6 When will you fix this problem?

From what I can guess, he seems to be busy developing version 2.0
