### ISSUE TITLE
player get kicked bug

### ISSUE THREAD

**Issue by YaliGaming** [PluginBugs/Issues-CosmeticsCore#25]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Yali Gaming#1492

### What happened?

player get kicked when exit in the wardrobe

### Steps to reproduce the issue

prass shift in the wardrobe

### Server version

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads

### CosmeticsCore Version

1.0.1-beta3

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.20

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/9628035/latest.log)

### Error (optional)

```shell
[20:08:54 INFO]: YaliGaming issued server command: /wardrobe
[20:08:54 ERROR]: [eco] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, java.util.function.UnaryOperator)'
        at com.willfp.eco.internal.spigot.display.PacketSetSlot.onSend(PacketSetSlot.kt:20) ~[eco-6.38.3-all.jar:?]
        at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.38.3-all.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2040) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2026) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:758) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:743) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:411) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:733) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:687) ~[ProtocolLib.jar:?]
        at dev.lone.cosmeticscore.nms.aL.aP.o(SourceFile:66) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.nms.aI.aO.a(SourceFile:165) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.nms.aI.aO.D(SourceFile:143) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.main.k.b(SourceFile:221) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.main.k.a(SourceFile:71) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.main.h.j(SourceFile:305) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.main.f.a(SourceFile:22) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at dev.lone.cosmeticscore.main.a.onCommand(SourceFile:26) ~[CosmeticsCore_1.0.1-beta3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### CosmeticsCore config.yml

```shell
lang: he
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -8927.5
      y: 79.62000000476837
      z: 5591.5
      yaw: 44.79755
      pitch: 2.7000904
  mannequin:
    location:
      world: world
      x: -8930.5
      y: 78.0
      z: 5594.5
      yaw: -133.85358
      pitch: 3.4500299
  teleport_area:
    enter:
      world: world
      pos1:
        x: -8917.0
        y: 72.0
        z: 5585.0
      pos2:
        x: -8917.0
        y: 73.0
        z: 5586.0
    exit_location:
      world: world
      x: -8917.5
      y: 72.0
      z: 5587.5
      yaw: -89.45221
      pitch: 2.6998892
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![צילום מסך 2022-09-22 200706](https://user-images.githubusercontent.com/70468515/191810392-538b7d88-fe54-4d82-8a36-9b251b8a8e82.png)

**Comment by YaliGaming** [comment]
I FOUND OUT THAT InteractiveChat (plugin) IS THE PROBLEM

**Comment by LoneDev6** [comment]
Thanks, please contact InteractiveChat developer and let them know.
