### ISSUE TITLE
CosmeticsCore causes server crash during activation

### ISSUE THREAD

**Issue by Jeremylo1** [PluginBugs/Issues-CosmeticsCore#257]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Jeremylo1

### What happened?

The CosmeticsCore plugin causes my server to crash upon activation. An error occurs in the `onEnable` method, indicating a problem during the plugin's loading process. It seems there may be a compatibility issue or a missing dependency, but the logs don't provide a clear indication of the cause. This makes it impossible to use the plugin on a Paper 1.21 server.

### Steps to reproduce the issue

1. Start the server with Paper version 1.21.
2. Install [LoneLibs](https://www.spigotmc.org/resources/lonelibs.75974/)
3. Install [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)
4. Install ItemsAdder
2. Add CosmeticsCore plugin (version 1.3.0-release-2).
3. The server tries to load the plugin, but an error occurs, leading to a server restart

### Server version

This server is running Paper version 1.21-119-100d75a (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version 1.3.0-release-2

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.58

### FULL server log

[2024-09-04-9.log](https://github.com/user-attachments/files/16880447/2024-09-04-9.log)

### Error (optional)

```shell
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more
[21:39:21] [ServerMain/INFO]: [FileProviderSource] The spark plugin will not be loaded as this server bundles the spark profiler.
[21:39:21] [ServerMain/INFO]: [PluginInitializerManager] Initialized 48 plugins
[21:39:21] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (48):
 - BeautyQuests (1.0.3), BetterHud (1.4), BetterRTP (3.6.13), BlueMap (3.21), BlueMapPlayerControl (1.5), CMILib (1.5.1.3), Citizens (2.0.35-SNAPSHOT (build 3545)), CoreProtect (22.0), CosmeticsCore (1.3.0-release-2), CyberWorldReset (0.6.2), DeluxeMenus (1.14.0-Release), DirectionalBlock (1.4.1), Essentials (2.21.0-dev+111-b54c8c1), EssentialsChat (2.21.0-dev+111-b54c8c1), EssentialsProtect (2.21.0-dev+111-b54c8c1), EssentialsSpawn (2.21.0-dev+111-b54c8c1), FastAsyncWorldEdit (2.11.2-SNAPSHOT-888;75fb1cb), FreedomChat (1.7.0), HMCColor (0.7), ItemsAdder (4.0.2-alpha-test-7), Jobs (5.2.4.2), Lands (7.9.9), LoneLibs (1.0.58), LuckPerms (5.4.128), Multiverse-Core (4.3.12), MythicMobs (5.7.1-${CI_COMMIT_SHORT_SHA}), MythicMobsGUI (1.9.8), PlaceholderAPI (2.11.6), Plan (5.6 build 2820), PlayerAuctions (1.28.1), ProCosmetics (14.0.6), ProtocolLib (5.3.0-SNAPSHOT-726), RPGhuds (1.2.0-r2), SkBee (3.6.1), Skript (2.9.2), TAB (4.1.8), UnifiedMetrics (0.3.8), UpgradeableHoppers (4.17.0), UpgradeableSpawners (4.14.9), Vault (1.7.3-b131), Votifier (2.7.3), VotingPlugin (6.17.1), WorldEditSelectionVisualizer (2.1.7), WorldGuard (7.0.11-SNAPSHOT+2287-8ffc81a), WorldGuardExtraFlags (4.2.4-SNAPSHOT), ore-control (2024.06.16), skript-placeholders (1.6.0), skript-reflect (2.4)
[21:39:24] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:39:25] [ServerMain/INFO]: Loaded 1290 recipes
[21:39:25] [ServerMain/INFO]: Loaded 1399 advancements
[21:39:25] [Server thread/INFO]: Starting minecraft server version 1.21

	at CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.Main.onEnable(SourceFile:54) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-119-100d75a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-119-100d75a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

========================================

	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.au.bN(SourceFile:40) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.Main.onEnable(SourceFile:54) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-119-100d75a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-119-100d75a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-119-100d75a]
```

### CosmeticsCore config.yml

```shell
I deleted the **CosmeticsCore** `config.yml` file to reset the configuration, but the plugin doesn't recreate the configuration files upon restart.
```

**Comment by Pedro33210** [comment]
up

**Comment by LoneDev6** [comment]
Update to 1.21.1 or 1.21.3.
This is not compatible with 1.21.
