### ISSUE TITLE
1.20.4 DataComponents Error

### ISSUE THREAD

**Issue by beautybloodtr** [PluginBugs/Issues-CosmeticsCore#264]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

x

### What happened?

CosmeticsCore, which works in my 1.20.2 game mode, does not work in my 1.20.4 game mode even though it is the latest version (ProtocolLib and LoneLibs are also up to date).

### Steps to reproduce the issue

```
[22:21:17] [Server thread/INFO]: [CosmeticsCore] Enabling CosmeticsCore v1.3.0-release-2
[22:21:18] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.3.0-release-2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.IDataComponents.setCustomName(org.bukkit.inventory.ItemStack, String)" because "lonelibs.dev.lone.fastnbt.nms.nbt.NBT.dataComponents" is null
	at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.setCustomName(NItem.java:182) ~[LoneLibs_1.0.58.jar:?]
	at dev.lone.cosmeticscore.main.aB.b(SourceFile:58) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at dev.lone.cosmeticscore.main.aB.a(SourceFile:44) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at dev.lone.cosmeticscore.b.d(SourceFile:124) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at dev.lone.cosmeticscore.Main.onEnable(SourceFile:60) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:21:18] [Server thread/INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.3.0-release-2
```

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2095 (MC: 1.20.2)
* You are running the latest version

### CosmeticsCore Version

1.3.0-release-2

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.58

### FULL server log

https://hastebin.com/share/ovivesecac.makefile

### Error (optional)

```shell
[22:21:17] [Server thread/INFO]: [CosmeticsCore] Enabling CosmeticsCore v1.3.0-release-2
[22:21:18] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.3.0-release-2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.IDataComponents.setCustomName(org.bukkit.inventory.ItemStack, String)" because "lonelibs.dev.lone.fastnbt.nms.nbt.NBT.dataComponents" is null
	at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.setCustomName(NItem.java:182) ~[LoneLibs_1.0.58.jar:?]
	at dev.lone.cosmeticscore.main.aB.b(SourceFile:58) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at dev.lone.cosmeticscore.main.aB.a(SourceFile:44) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at dev.lone.cosmeticscore.b.d(SourceFile:124) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at dev.lone.cosmeticscore.Main.onEnable(SourceFile:60) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:21:18] [Server thread/INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.3.0-release-2
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 1
    balloon: 1
    hats: 1
  hide_during_combat:
    enabled: true
    combat_duration_ticks: 10000
  fix_invisible_nametag: true
  hide_in_vanish: true
  worlds:
  - '*'
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world_nether
      x: 405.5
      y: 66.25154149831695
      z: 746.5
      yaw: 270.07535
      pitch: -1.4295385
    use_invisibility_potion: false
  mannequin:
    location:
      world: world_nether
      x: 410.5
      y: 65.0
      z: 746.5
      yaw: 89.093994
      pitch: 0.1071393
  teleport_area:
    enter:
      world: passion
      pos1:
        x: -9.0
        y: 73.0
        z: 30.0
      pos2:
        x: -12.0
        y: 71.0
        z: 30.0
    exit_location:
      world: world
      x: -8.87818389053755
      y: 71.0
      z: 28.82813475220093
      yaw: 13.532958
      pitch: -15.984814
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  file:
    enabled: false
  mysql:
    enabled: true
    url: (deleted for issues)
    username: 
    password: 
    table: c
debug: false
```

**Comment by beautybloodtr** [comment]
dude what time you can fix? i cant use the plugin at 2 weeks?

**Comment by LoneDev6** [comment]
Should have already been fixed on latest LoneLibs versions.
