### ISSUE TITLE
Plugin is not loaded in version 1.21

### ISSUE THREAD

**Issue by lackooka** [PluginBugs/Issues-CosmeticsCore#265]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

dlacoo

### What happened?

The plugin is not loaded

### Steps to reproduce the issue

1. 1.21 purpur server
2. latest plugins
3. errors show up and the szerver keeps crashing

### CosmeticsCore Version

[16:37:24 INFO]: Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*
* You are running the latest versionver

### ProtocolLib Version

[16:38:00 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[16:38:00 INFO]: Provides read/write access to the Minecraft protocol.
[16:38:00 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:37:49 INFO]: LoneLibs version 1.0.59
[16:37:49 INFO]: Collection of libs used by my plugins
[16:37:49 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/user-attachments/files/17090120/latest.log)

### Error (optional)

```shell
java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.au.bN(SourceFile:40) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.Main.onEnable(SourceFile:54) ~[CosmeticsCore_1.3.0-release-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by lackooka** [comment]
I tried with only 3 plugins (the main one and the depends) and I got this:
[latest.log](https://github.com/user-attachments/files/17090169/latest.log)

**Comment by LoneDev6** [comment]
Update to 1.21.1 or 1.21.3.
