### ISSUE TITLE
Cosmetics are not applying onto Helms with custom enchants on them.

### ISSUE THREAD

**Issue by MashesB** [PluginBugs/Issues-CosmeticsCore#272]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

MashesB#0775

### What happened?

When a players has a helmet with custom enchants (Echo Enchants Plugin) on it and is equipped in the helm slot the wardrobe room does no function correctly. It will show that the cosmetic helm is being applied but once u leave the wardrobe room the cosmetic isn't applied to the player. the plugin then glitches, leaves some error msgs in the console and you can see yourself in the wardrobe room with the cosmetic on while looking in.

### Steps to reproduce the issue

1: Go into wardrobe room
2: Apply cosmetic Helm
3: Leave wardrobe room (notice no cosmetic is applied)
4: A copy of the player will be in the wardrobe room with the cosmetic applied

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*

### CosmeticsCore Version

1.3.0-release-1  

(R2 doesn't work for me, I have the same issue with that version that others are posting about in Discord and Github)

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.59

### FULL server log

[latest.log](https://github.com/user-attachments/files/17689208/latest.log)

### Error (optional)

```shell
[11:51:02 WARN]: [CosmeticsCore] Task #322802 for CosmeticsCore v1.3.0-release-1 generated an exception
java.lang.ClassCastException: class io.papermc.paper.adventure.AdventureComponent cannot be cast to class net.minecraft.network.chat.IChatMutableComponent (io.papermc.paper.adventure.AdventureComponent and net.minecraft.network.chat.IChatMutableComponent are in unnamed module of loader java.net.URLClassLoader @7e32c033)
        at dev.lone.cosmeticscore.nms.aH.impl.v1_20_4.a(SourceFile:378) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at dev.lone.cosmeticscore.nms.aH.impl.v1_20_4.a(SourceFile:376) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.nms.aH.impl.v1_20_4.a(SourceFile:224) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.y.a(SourceFile:165) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.y.c(SourceFile:145) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.y.m(SourceFile:93) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.y.a(SourceFile:103) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.y.setColor(SourceFile:38) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.y.<init>(SourceFile:31) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.af.a(SourceFile:42) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.j.a(SourceFile:542) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.l.D(SourceFile:155) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at dev.lone.cosmeticscore.main.l.K(SourceFile:221) ~[CosmeticsCore_1.3.0-release-1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### CosmeticsCore config.yml

```shell
cosmetics:
  evergreen_crown_cosmetic:
    enabled: true
    display_name: " Evergreen Crown  [Cosmetic]"
    type: HAT
    model:
      gui: evergreenset:evergreen_crown
      normal: evergreenset:evergreen_crown
    dye:
      enabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/07ea397d-7f62-464f-882c-79fcb43b43f2

**Comment by LoneDev6** [comment]
Please report it again if the issue still occurs.
This is quite strange as the type is correct.

![Image](https://github.com/user-attachments/assets/cd0795d3-db6b-47e9-ad26-3d4ce7c883bc)
