### ISSUE TITLE
can dupe the tutorial

### ISSUE THREAD

**Issue by YaliGaming** [PluginBugs/Issues-CosmeticsCore#30]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Yali Gaming#1492

### What happened?

you can dupe the tutorial when going on 9th slot and press other slot numbers

### Steps to reproduce the issue

go to the 9th slot
and just press other inventory slots number

### Server version

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads

### CosmeticsCore Version

1.0.1-beta3

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.20

### FULL server log

[09:13:04] [Server thread/INFO]: YaliGaming issued server command: /wardrobe
[09:13:05] [Server thread/ERROR]: [eco] Unhandled exception number 512 occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, java.util.function.UnaryOperator)'
	at com.willfp.eco.internal.spigot.display.PacketHeldWindowItems.onSend(PacketHeldWindowItems.kt:19) ~[eco-6.41.1-all.jar:?]
	at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.41.1-all.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2040) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2026) ~[?:?]
	at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:273) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:202) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.updateInventory(CraftPlayer.java:1231) ~[paper-1.18.2.jar:git-Paper-387]
	at dev.lone.cosmeticscore.main.o.a(SourceFile:343) ~[CosmeticsCore_1.0.1-beta3.jar:?]
	at dev.lone.cosmeticscore.main.o.N(SourceFile:167) ~[CosmeticsCore_1.0.1-beta3.jar:?]
	at dev.lone.cosmeticscore.main.k.I(SourceFile:415) ~[CosmeticsCore_1.0.1-beta3.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:13:30] [Craft Scheduler Thread - 116 - Infiniteannouncements/WARN]: [Infiniteannouncements] Plugin Infiniteannouncements v2.3.1 generated an exception while executing task 91
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.zachfr.infiniteannouncements.announcements.AnnouncementManager.lambda$loadAnnouncements$0(AnnouncementManager.java:60) ~[infiniteannouncements-2.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:14:30] [Craft Scheduler Thread - 86 - Infiniteannouncements/WARN]: [Infiniteannouncements] Plugin Infiniteannouncements v2.3.1 generated an exception while executing task 91
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.zachfr.infiniteannouncements.announcements.AnnouncementManager.lambda$loadAnnouncements$0(AnnouncementManager.java:60) ~[infiniteannouncements-2.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:15:30] [Craft Scheduler Thread - 102 - Infiniteannouncements/WARN]: [Infiniteannouncements] Plugin Infiniteannouncements v2.3.1 generated an exception while executing task 91
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.zachfr.infiniteannouncements.announcements.AnnouncementManager.lambda$loadAnnouncements$0(AnnouncementManager.java:60) ~[infiniteannouncements-2.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:16:30] [Craft Scheduler Thread - 105 - Infiniteannouncements/WARN]: [Infiniteannouncements] Plugin Infiniteannouncements v2.3.1 generated an exception while executing task 91
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.zachfr.infiniteannouncements.announcements.AnnouncementManager.lambda$loadAnnouncements$0(AnnouncementManager.java:60) ~[infiniteannouncements-2.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:16:48] [Server thread/INFO]: Named entity EntitySkeletonWither['Skeletal Knight'/3155, uuid='3cdb8a03-96ba-4a9d-bc2c-88242bcefcbc', l='ServerLevel[world]', x=-8949.50, y=30.00, z=5594.50, cpos=[-560, 349], tl=482, v=true] died: Skeletal Knight suffocated in a wall
[09:17:02] [Server thread/INFO]: YaliGaming issued server command: /day
[09:17:03] [Server thread/INFO]: YaliGaming issued server command: /sun
[09:17:06] [Server thread/INFO]: YaliGaming issued server command: /version
[09:17:15] [Server thread/INFO]: YaliGaming issued server command: /killall mobs
[09:17:18] [Server thread/INFO]: YaliGaming issued server command: /killall arrows
[09:17:28] [Server thread/INFO]: YaliGaming issued server command: /version CosmeticsCore
[09:17:30] [Craft Scheduler Thread - 120 - Infiniteannouncements/WARN]: [Infiniteannouncements] Plugin Infiniteannouncements v2.3.1 generated an exception while executing task 91
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.zachfr.infiniteannouncements.announcements.AnnouncementManager.lambda$loadAnnouncements$0(AnnouncementManager.java:60) ~[infiniteannouncements-2.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:17:41] [Server thread/INFO]: YaliGaming issued server command: /version ItemsAdder
[09:17:44] [Server thread/INFO]: YaliGaming issued server command: /version ProtocolLib
[09:17:56] [Server thread/INFO]: YaliGaming issued server command: /version LoneLibs

### CosmeticsCore config.yml

```shell
lang: he
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -8927.5
      y: 79.62000000476837
      z: 5591.5
      yaw: 44.79755
      pitch: 2.7000904
  mannequin:
    location:
      world: world
      x: -8930.5
      y: 78.0
      z: 5594.5
      yaw: -133.85358
      pitch: 3.4500299
  teleport_area:
    enter:
      world: world
      pos1:
        x: -8917.0
        y: 72.0
        z: 5585.0
      pos2:
        x: -8917.0
        y: 73.0
        z: 5586.0
    exit_location:
      world: world
      x: -8917.5
      y: 72.0
      z: 5587.5
      yaw: -89.45221
      pitch: 2.6998892
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/70468515/192206433-6567c56e-e028-486c-8ed5-f422e6222f10.png)

**Comment by LoneDev6** [comment]
` [eco] Unhandled exception number 512 occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier`

This error is from another plugin, fix it.

**Comment by YaliGaming** [comment]
In general, it is possible to reproduce, it is not related
