### ISSUE TITLE
plugin in error

### ISSUE THREAD

**Issue by axin0452** [PluginBugs/Issues-CosmeticsCore#31]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

[09:28:35 ERROR]: [CosmeticsCore] Unhandled exception occurred in onPacketSending(PacketEvent) for CosmeticsCore
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.e(String)" because the return value of "net.minecraft.world.item.ItemStack.u()" is null
        at dev.lone.cosmeticscore.nms.aI.impl.v1_19_R1.a(SourceFile:367) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.x.b(SourceFile:144) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.C.onPacketSending(SourceFile:158) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[【前置】ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:430) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:540) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:503) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:398) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2163) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2149) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.onUpdateAbilities(ServerPlayer.java:1821) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.setGameModeForPlayer(ServerPlayerGameMode.java:103) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.changeGameModeForPlayer(ServerPlayerGameMode.java:94) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.setGameMode(ServerPlayer.java:1837) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:1554) ~[paper-1.19.2.jar:git-Paper-138]
        at com.francobm.magiccrates.nms.v1_19_R1.VersionHandler.setSpectator(VersionHandler.java:47) ~[【材质】【抽奖】MagicCrates-1.3.4.B5.jar:?]
        at com.francobm.magiccrates.cache.PlayerCache$1.run(PlayerCache.java:647) ~[【材质】【抽奖】MagicCrates-1.3.4.B5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:28:35 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutSetSlot@14a175a5[
    c=0
    d=45
    e=5
    f=1 air
  ]

[09:28:35 ERROR]: [CosmeticsCore] Unhandled exception occurred in onPacketSending(PacketEvent) for CosmeticsCore
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.e(String)" because the return value of "net.minecraft.world.item.ItemStack.u()" is null
        at dev.lone.cosmeticscore.nms.aI.impl.v1_19_R1.a(SourceFile:367) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.x.b(SourceFile:144) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.A.onPacketSending(SourceFile:68) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[【前置】ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2163) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2149) ~[?:?]
        at dev.lone.cosmeticscore.nms.aI.impl.v1_19_R1.a(SourceFile:75) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.nms.aI.impl.v1_19_R1.b(SourceFile:48) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.nms.aI.aO.b(SourceFile:78) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.nms.aG.impl.v1_19_R1.a(SourceFile:256) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.x.h(SourceFile:94) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.x.a(SourceFile:100) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.i.a(SourceFile:390) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.z.a(SourceFile:228) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.z.a(SourceFile:284) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-138]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1262) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1173) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.entity.Entity.teleport(Entity.java:156) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1168) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:538) ~[paper-1.19.2.jar:git-Paper-138]
        at com.francobm.magiccrates.cache.PlayerCache$1.run(PlayerCache.java:651) ~[【材质】【抽奖】MagicCrates-1.3.4.B5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:28:35 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntityEquipment@46f9ef6c[
    b=56
    c=[(HEAD, 1 splash_potion)]
  ]

[09:28:35 ERROR]: [CosmeticsCore] Unhandled exception occurred in onPacketSending(PacketEvent) for CosmeticsCore
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.e(String)" because the return value of "net.minecraft.world.item.ItemStack.u()" is null
        at dev.lone.cosmeticscore.nms.aI.impl.v1_19_R1.a(SourceFile:367) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.x.b(SourceFile:144) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.C.onPacketSending(SourceFile:158) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[【前置】ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[【前置】ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:430) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:540) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:503) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:398) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2163) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2149) ~[?:?]
        at dev.lone.itemsadder.NMS.aD.impl.v1_19_R1_2.a(SourceFile:602) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.NMS.aD.impl.v1_19_R1_2.f(SourceFile:233) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.main.bb.f(SourceFile:553) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.main.aI.b(SourceFile:658) ~[【材质】itemsadder_3_2_3n.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at dev.lone.itemsadder.main.aI.c(SourceFile:653) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.main.aI.M(SourceFile:639) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.main.aI.a(SourceFile:1091) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.main.aH.a(SourceFile:1118) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.itemsadder.api.CustomEntity.destroy(SourceFile:330) ~[【材质】itemsadder_3_2_3n.jar:?]
        at dev.lone.cosmeticscore.main.w.s(SourceFile:320) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at dev.lone.cosmeticscore.main.h.m(SourceFile:505) ~[【材质】【时装】CosmeticsCore_1.0.1-beta2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:28:35 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutSetSlot@31d727b[
    c=0
    d=47
    e=5
    f=1 carved_pumpkin
  ]

### Steps to reproduce the issue

Cosmticscore will report an error when I open the lottery box plug-in

### CosmeticsCore Version

CosmeticsCore_1.0.1-beta3

### ProtocolLib Version

ProtocolLib600

### LoneLibs Version

name: LoneLibs
version: 1.0.21

**Comment by LoneDev6** [comment]
Post it as text not screenshots.

**Comment by axin0452** [comment]
@LoneDev6 Sorry, I edited it again
