### ISSUE TITLE
Sometimes portals stop working

### ISSUE THREAD

**Issue by DarkyCat** [PluginBugs/Issues-CosmeticsCore#45]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Sometimes the player will not be able to enter the portal and such an error appears.

### Steps to reproduce the issue

When the player enters the portal

### Server version

Purpur 1.19.2

### CosmeticsCore Version

1.0.2

### ProtocolLib Version

5.0.0-b600

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[23:18:29 WARN]: [CosmeticsCore] Task #49452 for CosmeticsCore v1.0.2-beta generated an exception
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.api.CustomEntity.getBones()" because "this.a" is null
   at dev.lone.cosmeticscore.main.v.getColor(SourceFile:40) ~[cosmetics.jar:?]
   at dev.lone.cosmeticscore.main.i.a(SourceFile:453) ~[cosmetics.jar:?]
   at dev.lone.cosmeticscore.main.k.b(SourceFile:103) ~[cosmetics.jar:?]
   at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.lambda$spin$
[23:19:57 ERROR]: Could not pass event PlayerQuitEvent to CosmeticsCore v1.0.2-beta
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.api.CustomEntity.getBones()" because "this.a" is null
   at dev.lone.cosmeticscore.main.v.getColor(SourceFile:40) ~[cosmetics.jar:?]
   at dev.lone.cosmeticscore.main.U.d(SourceFile:37) ~[cosmetics.jar:?]
   at dev.lone.cosmeticscore.main.i.c(SourceFile:279) ~[cosmetics.jar:?]
   at dev.lone.cosmeticscore.main.z.a(SourceFile:218) ~[cosmetics.jar:?]
   at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1814]
   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
   at net.minecraft.server.players.PlayerList.remove(PlayerList.java:630) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.players.PlayerList.remove(PlayerList.java:613) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2219) ~[?:?]
   at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2199) ~[?:?]
   at net.minecraft.network.Connection.handleDisconnection(Connection.java:778) ~[?:?]
   at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]
   at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1814]
   at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Post the complete log, I'm sure there is another error before.
Seems the itemsadder entity failed to load, probably it doesn't exists.

**Comment by DarkyCat** [comment]
> Post the complete log, I'm sure there is another error before. Seems the itemsadder entity failed to load, probably it doesn't exists.

The problem was presumably related to /iareloadThe problem was presumably related to /iareload

**Comment by LoneDev6** [comment]
Should be fixed
