### ISSUE TITLE
CosmeticsCore gives error on startup and disables itself

### ISSUE THREAD

**Issue by notdeliable** [PluginBugs/Issues-CosmeticsCore#51]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Deliable#1111

### What happened?

CosmeticsCore gives error on startup and disables itself

### Steps to reproduce the issue

1. Start the server

### Server version

Current: git-Purpur-1825 (MC: 1.19.2)*
* You are running the latest version

### CosmeticsCore Version

CosmeticsCore version 1.0.3

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

### Error (optional)

```shell
[13:45:35] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.0.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.main.aB.c(String)" because the return value of "dev.lone.itemsadder.main.aB.a()" is null
	at dev.lone.itemsadder.api.CustomStack.getOriginal(SourceFile:60) ~[?:?]
	at dev.lone.itemsadder.api.CustomStack.getInstance(SourceFile:98) ~[?:?]
	at dev.lone.cosmeticscore.main.ab.a(SourceFile:34) ~[?:?]
	at dev.lone.cosmeticscore.main.aa.a(SourceFile:48) ~[?:?]
	at dev.lone.cosmeticscore.b.b(SourceFile:93) ~[?:?]
	at dev.lone.cosmeticscore.Main.onEnable(SourceFile:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:45:35] [Server thread/INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.0.3
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

**Comment by notdeliable** [comment]
It got fixed when I ran it on another machine.
