### ISSUE TITLE
Air cosmetics bug

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#52]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Air cosmetics are not selected when choosing.

### Steps to reproduce the issue

Fix the error

### Server version

Current: git-Purpur-1819 (MC: 1.19.2)*
* You are 6 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### CosmeticsCore Version

1.0.3

### ProtocolLib Version

5.0.0-b602

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[19:05:31] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.21
java.lang.NullPointerException: Cannot read field "B" because "this.a" is null
	at dev.lone.itemsadder.main.aJ.a(SourceFile:234) ~[ItemsAdder_3.2.4-beta1.jar:?]
	at dev.lone.itemsadder.main.aJ.b(SourceFile:183) ~[ItemsAdder_3.2.4-beta1.jar:?]
	at dev.lone.itemsadder.main.aH.a(SourceFile:420) ~[ItemsAdder_3.2.4-beta1.jar:?]
	at dev.lone.itemsadder.api.CustomEntity.spawn(SourceFile:97) ~[ItemsAdder_3.2.4-beta1.jar:?]
	at dev.lone.cosmeticscore.main.t.R(SourceFile:57) ~[CosmeticsCore_1.0.3 (1).jar:?]
	at dev.lone.cosmeticscore.main.O.a(SourceFile:29) ~[CosmeticsCore_1.0.3 (1).jar:?]
	at dev.lone.cosmeticscore.main.o.a(SourceFile:423) ~[CosmeticsCore_1.0.3 (1).jar:?]
	at dev.lone.cosmeticscore.main.o.a(SourceFile:309) ~[CosmeticsCore_1.0.3 (1).jar:?]
	at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[LoneLibs (9).jar:?]
	at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[LoneLibs (9).jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1819]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3401) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1819]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: 138.63990002842772
      y: 106.62000000476837
      z: 140.09620867428632
      yaw: 149.14052
      pitch: 5.52394
  mannequin:
    location:
      world: world
      x: 136.5
      y: 105.0
      z: 136.5
      yaw: 31
      pitch: 0
  teleport_area:
    enter:
      world: world
      pos1:
        x: 140.0
        y: 105.0
        z: 140.0
      pos2:
        x: 140.0
        y: 105.0
        z: 137.0
    exit_location:
      world: world
      x: 142.46718007570996
      y: 105.0
      z: 138.96760077122525
      yaw: -89.405365
      pitch: -1.488256
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
# Example custom balloon created with ItemsAdder entities (supports also animated ItemsAdder entities models)
  amogus_balloon:
    display_name: "Amogus Balloon"
    type: BALLOON_ENTITY
    # Showing a different item into the GUI (in this case it's a must because ItemsAdder entities can't be put in GUIs)
    model:
      gui: potion:400014
      normal: cosmetics:amogus
    dye:
      enabled: true
      default: "#ff0000"
```

**Comment by LoneDev6** [comment]
Probably the entity failed to load because of some misconfiguration.
Read the full log before that error.
Provide here the full log if you cannot find the cause.
