### ISSUE TITLE
ItemsAdder + Lonelibs + Cosmetics + protolib + CMI + Skript  = Crash (itemsadder + cosmetics) 

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-CosmeticsCore#73]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

It is not available if you run cosematics and script or cmi together.

Not only cosmetics but also itemsadder are not available.
How can I solve this problem?

### Steps to reproduce the issue

ItemsAdder + Lonelibs + Cosmetics + protolib = OK
ItemsAdder + Lonelibs + Cosmetics + protolib +  Skript  = OK
ItemsAdder + Lonelibs + Cosmetics + protolib + CMI   = OK
ItemsAdder + Lonelibs + Cosmetics + protolib + Skript + Essential  = OK

ItemsAdder + Lonelibs + Cosmetics + protolib + CMI + Skript  = Crash (itemsadder + cosmetics) 

### CosmeticsCore Version

CosmeticsCore 1.0.5

### ProtocolLib Version

#608

### LoneLibs Version

1.0.22

### Error (optional)

```shell
[00:02:22] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.0.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:36) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at dev.lone.cosmeticscore.main.E.f(SourceFile:22) ~[CosmeticsCore_1.0.5.jar:?]
	at dev.lone.cosmeticscore.main.j.b(SourceFile:261) ~[CosmeticsCore_1.0.5.jar:?]
	at dev.lone.cosmeticscore.Main.onEnable(SourceFile:50) ~[CosmeticsCore_1.0.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-258]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.a()" is null
	at ia.m.I.<clinit>(SourceFile:108) ~[ItemsAdder_3.3.0b-r2.jar:?]
	... 15 more
[00:02:22] [Server thread/INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.0.5
```

### Problematic items yml configuration file (optional)

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

**Comment by Lerphie** [comment]
Согласен! У меня такая-же ошибка

**Comment by Ecilpse** [comment]
i have same problems after updated IA 3.3.0 R8.
This error occurs when cmi, cmilib, jobs, jetsminions are installed in server.

**Comment by Ecilpse** [comment]
ItemsAdder + Lonelibs + Cosmetics + protolib + CMI + CMIlib = worked.
ItemsAdder + Lonelibs + Cosmetics + protolib + CMI + CMIlib + jobs = broken
ItemsAdder + Lonelibs + Cosmetics + protolib + CMI + CMIlib + jetsminions = broken

**Comment by Ecilpse** [comment]
> 

i think it's not caused by cosmeticscore. after update IA to lastest version, this errors was happend.

**Comment by LoneDev6** [comment]
> I cannot identify the cause without the full logs of when the issue occurred. Please share the correct log.

**Comment by Ecilpse** [comment]
> > I cannot identify the cause without the full logs of when the issue oc
[2022-12-29-27.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10362404/2022-12-29-27.log)
curred. Please share the correct log.

**Comment by l3st4tDevelopment** [comment]
I have the same issue - here's the log: https://pastebin.com/2Fdw7cJG

**Comment by LoneDev6** [comment]
Thanks I'm trying to find the cause, this is a very odd issue.

**Comment by Akiranya** [comment]
> Seems somehow CosmeticsCore is loading BEFORE ItemsAdder... this is extremely strange. This seems to happen only on some particular servers.

This is because `softpend` doesn't guarantee the loading order. Only `depend` does.

A possible solution would be adding `CosmeticsCore` in the `loadbefore` of ItemsAdder's plugin.yml

**Comment by LoneDev6** [comment]
> > Seems somehow CosmeticsCore is loading BEFORE ItemsAdder... this is extremely strange. This seems to happen only on some particular servers.
> 
> This is because `softpend` doesn't guarantee the loading order. Only `depend` does.
> 
> A possible solution would be adding `CosmeticsCore` in the `loadbefore` of ItemsAdder's plugin.yml


I thought `loadbefore` required plugins to be installed and throws errors if they are not.

**Comment by Akiranya** [comment]
> > > Seems somehow CosmeticsCore is loading BEFORE ItemsAdder... this is extremely strange. This seems to happen only on some particular servers.
> > 
> > 
> > This is because `softpend` doesn't guarantee the loading order. Only `depend` does.
> > A possible solution would be adding `CosmeticsCore` in the `loadbefore` of ItemsAdder's plugin.yml
> 
> I thought `loadbefore` required plugins to be installed and throws errors if they are not.

No it's safe to use `loadbefore` even if the plugin is not installed. I have a homemade plugin using this option and it works well :D

**Comment by LoneDev6** [comment]
@Akiranya 
Interesting, thanks!
I'll do some testing again
