### ISSUE TITLE
Problem with Vulcan

### ISSUE THREAD

**Issue by Osmanto123** [PluginBugs/Issues-CosmeticsCore#76]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Osmanto#4263

### What happened?

It won't start

### Steps to reproduce the issue

1 - Open config.yml of Vulcan and set enable-api: true 
2 - Start the server

### Server version

This server is running Pufferfish version git-Pufferfish-42 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: dda277a on HEAD)

### CosmeticsCore Version

CosmeticsCore version 1.0.5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.22

### Error (optional)

```shell
[02:26:19 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[02:26:19 ERROR]: Error occurred while enabling CosmeticsCore v1.0.5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.frep.vulcan.api.VulcanAPI.getEnabledChecks()" because the return value of "me.frep.vulcan.api.VulcanAPI$Factory.getApi()" is null
        at dev.lone.cosmeticscore.main.aa.<init>(SourceFile:25) ~[CosmeticsCore_1.0.5.jar:?]
        at dev.lone.cosmeticscore.main.aa.c(SourceFile:20) ~[CosmeticsCore_1.0.5.jar:?]
        at dev.lone.cosmeticscore.main.Y.b(SourceFile:16) ~[CosmeticsCore_1.0.5.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:46) ~[CosmeticsCore_1.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

**Comment by LoneDev6** [comment]
Make sure you are using the latest Vulkan.
Anyway I'll do some tests, maybe something changed on their end.

**Comment by haroldrc** [comment]
same problem

**Comment by haroldrc** [comment]
things i noticed:

- disabling the punish of vulcan cosmetic core does not start

**Comment by LoneDev6** [comment]
Fixed in the upcoming version
