### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-CosmeticsCore#79]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

DinoBoss#6985

### What happened?

By placing cosmeticcore now loads cosmeticcore alone but itemsadder is disabled.

### Steps to reproduce the issue

1 Place cosmeticcore in your plugins folder.
2 Place itemsadders in your plugins folder.

Note: Previously both were deactivated.

### Server version

[10:48:30 INFO]: This server is running Paper version git-Paper-365 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 90750a6)

### CosmeticsCore Version

[10:48:53 INFO]: CosmeticsCore version 1.0.6-r2

### ProtocolLib Version

[10:49:14 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[10:49:14 INFO]: Provides read/write access to the Minecraft protocol.
[10:49:14 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

10:49:26 INFO]: LoneLibs version 1.0.23
[10:49:26 INFO]: Collection of libs used by my plugins
[10:49:26 INFO]: Authors: LoneDev and others

### FULL server log

https://mcpaste.io/84cddb3e006aeb31

### Error (optional)

```shell
[10:44:10 ERROR]: Error occurred while enabling ItemsAdder v3.3.0b-r3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
        at dev.lone.itemsadder.Main.onEnable(SourceFile:433) ~[ItemsAdder_3.3.0b-r3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-365]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at ia.m.I.<clinit>(SourceFile:108) ~[ItemsAdder_3.3.0b-r3.jar:?]
        at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:36) ~[ItemsAdder_3.3.0b-r3.jar:?]
        at dev.lone.cosmeticscore.main.E.Y(SourceFile:34) ~[CosmeticsCore_1.0.6-r2.jar:?]
        at dev.lone.cosmeticscore.main.j.b(SourceFile:261) ~[CosmeticsCore_1.0.6-r2.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:50) ~[CosmeticsCore_1.0.6-r2.jar:?]
        ... 11 more
[10:44:10 INFO]: [ItemsAdder] Disabling ItemsAdder v3.3.0b-r3
```

### Other files, you can drag and drop them here to upload. (optional)

default

### Screenshots/Videos (you can drag and drop files or paste links)

I don't think it is necessary, if it is, let us know.

**Comment by LoneDev6** [comment]
The error is totally different

**Comment by LoneDev6** [comment]
Please test the new r3 update.
This is extremely strange to be honest... something's wrong on your server definitely.

Download here: https://www.spigotmc.org/resources/cosmeticscore.105324/
