### ISSUE TITLE
Problem with backpack

### ISSUE THREAD

**Issue by haroldrc** [PluginBugs/Issues-CosmeticsCore#82]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

harold#1385

### What happened?

idk

### Steps to reproduce the issue

idk

### Server version

This server is running Pufferfish version git-Pufferfish-42 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### CosmeticsCore Version

1.0.6-r4

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.22

### Error (optional)

```shell
[01:30:55 ERROR]: [CosmeticsCore] Failed to load cosmetic weekend_cosmetic_green_surfboard. File: /cosmetics/weekend_cosmetic.yml
[01:30:55 WARN]: java.lang.IllegalArgumentException: Unknown self item for body cosmetic: elitecreatures:weekend_cosmetic_green_surfboard_self
[01:30:55 WARN]:        at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.R.<init>(SourceFile:35)
[01:30:55 WARN]:        at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.M.a(SourceFile:90)
[01:30:55 WARN]:        at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.j.a(SourceFile:231)
[01:30:55 WARN]:        at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.j.a(SourceFile:216)
[01:30:55 WARN]:        at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.d.a(SourceFile:42)
[01:30:55 WARN]:        at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.b.onCommand(SourceFile:26)
[01:30:55 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:30:55 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:30:55 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[01:30:55 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[01:30:55 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[01:30:55 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[01:30:55 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[01:30:55 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2295)
[01:30:55 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
[01:30:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[01:30:55 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[01:30:55 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:30:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:30:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1343)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[01:30:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1320)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1313)
[01:30:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1291)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1179)
[01:30:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[01:30:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: Partea
      x: -96.53276058731863
      y: 67.62000000476837
      z: -194.2617914999204
      yaw: 179.33032
      pitch: 4.200009
  mannequin:
    location:
      world: Partea
      x: -96.4752472737847
      y: 66.0
      z: -198.7875842024327
      yaw: 1.5796509
      pitch: -5.2499666
  teleport_area:
    enter:
      world: Partea
      pos1:
        x: -101.0
        y: 69.0
        z: -194.0
      pos2:
        x: -92.0
        y: 66.0
        z: -194.0
    exit_location:
      world: Partea
      x: -99.25624387167402
      y: 66.0
      z: -191.65020282466318
      yaw: 40.766907
      pitch: -6.767159
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
cosmetics:

  # Blue

  weekend_cosmetic_blue_backpack:
    display_name: "[Weekend] Blue Backpack"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_blue_backpack
      normal: elitecreatures:weekend_cosmetic_blue_backpack
      self: elitecreatures:weekend_cosmetic_blue_backpack_self
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_blue_glasses_1:
    display_name: "[Weekend] Blue Glasses 1"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_blue_glasses_1
      normal: elitecreatures:weekend_cosmetic_blue_glasses_1
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_blue_glasses_2:
    display_name: "[Weekend] Blue Glasses 2"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_blue_glasses_2
      normal: elitecreatures:weekend_cosmetic_blue_glasses_2
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_blue_surfboard:
    display_name: "[Weekend] Blue Surfboard"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_blue_surfboard
      normal: elitecreatures:weekend_cosmetic_blue_surfboard
      self: elitecreatures:weekend_cosmetic_blue_surfboard_self
    dye:
      enabled: false
      default: "#000000"

  # Brown

  weekend_cosmetic_brown_backpack:
    display_name: "[Weekend] Brown Backpack"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_brown_backpack
      normal: elitecreatures:weekend_cosmetic_brown_backpack
      self: elitecreatures:weekend_cosmetic_brown_backpack_self
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_brown_glasses_1:
    display_name: "[Weekend] Brown Glasses 1"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_brown_glasses_1
      normal: elitecreatures:weekend_cosmetic_brown_glasses_1
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_brown_glasses_2:
    display_name: "[Weekend] Brown Glasses 2"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_brown_glasses_2
      normal: elitecreatures:weekend_cosmetic_brown_glasses_2
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_brown_surfboard:
    display_name: "[Weekend] Brown Surfboard"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_brown_surfboard
      normal: elitecreatures:weekend_cosmetic_brown_surfboard
      self: elitecreatures:weekend_cosmetic_brown_surfboard_self
    dye:
      enabled: false
      default: "#000000"

  # Gold

  weekend_cosmetic_gold_backpack:
    display_name: "[Weekend] Gold Backpack"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_gold_backpack
      normal: elitecreatures:weekend_cosmetic_gold_backpack
      self: elitecreatures:weekend_cosmetic_gold_backpack_self
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_gold_glasses_1:
    display_name: "[Weekend] Gold Glasses 1"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_gold_glasses_1
      normal: elitecreatures:weekend_cosmetic_gold_glasses_1
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_gold_glasses_2:
    display_name: "[Weekend] Gold Glasses 2"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_gold_glasses_2
      normal: elitecreatures:weekend_cosmetic_gold_glasses_2
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_gold_surfboard:
    display_name: "[Weekend] Gold Surfboard"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_gold_surfboard
      normal: elitecreatures:weekend_cosmetic_gold_surfboard
      self: elitecreatures:weekend_cosmetic_gold_surfboard_self
    dye:
      enabled: false
      default: "#000000"

  # Green

  weekend_cosmetic_green_backpack:
    display_name: "[Weekend] Green Backpack"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_green_backpack
      normal: elitecreatures:weekend_cosmetic_green_backpack
      self: elitecreatures:weekend_cosmetic_green_backpack_self
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_green_glasses_1:
    display_name: "[Weekend] Green Glasses 1"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_green_glasses_1
      normal: elitecreatures:weekend_cosmetic_green_glasses_1
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_green_glasses_2:
    display_name: "[Weekend] Green Glasses 2"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_green_glasses_2
      normal: elitecreatures:weekend_cosmetic_green_glasses_2
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_green_surfboard:
    display_name: "[Weekend] Green Surfboard"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_green_surfboard
      normal: elitecreatures:weekend_cosmetic_green_surfboard
      self: elitecreatures:weekend_cosmetic_green_surfboard_self
    dye:
      enabled: false
      default: "#000000"

  # Red

  weekend_cosmetic_red_backpack:
    display_name: "[Weekend] Red Backpack"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_red_backpack
      normal: elitecreatures:weekend_cosmetic_red_backpack
      self: elitecreatures:weekend_cosmetic_red_backpack_self
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_red_glasses_1:
    display_name: "[Weekend] Red Glasses 1"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_red_glasses_1
      normal: elitecreatures:weekend_cosmetic_red_glasses_1
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_red_glasses_2:
    display_name: "[Weekend] Red Glasses 2"
    type: HAT
    model:
      gui: elitecreatures:weekend_cosmetic_red_glasses_2
      normal: elitecreatures:weekend_cosmetic_red_glasses_2
    dye:
      enabled: false
      default: "#000000"
  weekend_cosmetic_red_surfboard:
    display_name: "[Weekend] Red Surfboard"
    type: BODY_ITEM
    model:
      gui: elitecreatures:weekend_cosmetic_red_surfboard
      normal: elitecreatures:weekend_cosmetic_red_surfboard
      self: elitecreatures:weekend_cosmetic_red_surfboard_self
    dye:
      enabled: false
      default: "#000000"
```

**Comment by LoneDev6** [comment]
The item `weekend_cosmetic_green_surfboard_self` doesn't exists in the configuration file and the plugin error is extremely clear about it.
Please avoid opening issues without first testing.

Thanks and have a nice day.
