### ISSUE TITLE
Problem with vulcan api & shift 

### ISSUE THREAD

**Issue by haroldrc** [PluginBugs/Issues-CosmeticsCore#83]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

harold#1385

### What happened?

- vulcan api problems
- shift doesn't work 

### Steps to reproduce the issue

enter the dressing room and press shift to exit (shift won't work)

### Server version

running Pufferfish version git-Pufferfish-42 (MC: 1.19.2)

### CosmeticsCore Version

1.0.6-r4

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.22

### Error (optional)

```shell
[06:07:54] [Server thread/ERROR]: [CosmeticsCore] [0;31mFailed to check Vulcan anticheat compatibility[0m
[06:07:54] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "me.frep.vulcan.api.VulcanAPI.getEnabledChecks()" because the return value of "me.frep.vulcan.api.VulcanAPI$Factory.getApi()" is null
[06:07:54] [Server thread/WARN]: 	at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.aa.<init>(SourceFile:27)
[06:07:54] [Server thread/WARN]: 	at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.aa.c(SourceFile:20)
[06:07:54] [Server thread/WARN]: 	at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.main.Y.b(SourceFile:16)
[06:07:54] [Server thread/WARN]: 	at CosmeticsCore_1.0.6-r4.jar//dev.lone.cosmeticscore.Main.onEnable(SourceFile:46)
[06:07:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[06:07:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[06:07:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[06:07:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[06:07:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[06:07:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[06:07:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[06:07:54] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[06:07:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1102)
[06:07:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[06:07:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
Check if you are using the latest Vulcan version.
Also send the FULL server log of when the issue occurred, not only a part of it.

**Comment by haroldrc** [comment]
https://pastebin.com/xaHPJsKR

**Comment by LoneDev6** [comment]
Somehow Vulcan is enabling after CosmeticsCore on your server.
This triggers this particular issue.

I'll try to find a solution for this strange occasion.

**Comment by haroldrc** [comment]
https://pastebin.com/XvqagAH6
