### ISSUE TITLE
Wardrobe - Vulcan AntiCheat false positive ("Bad Packets (Type V)")

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-CosmeticsCore#9]
### What happened?

When a player without Vulcan bypass permissions try to use `/wardrobe`, Vulcan flags them as cheating and shortly after kicks them from the server.

Server logs (replaced our user's name with "(player)".
```
[19:05:24] [Server thread/INFO]: (player) issued server command: /wardrobe
[19:05:25] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (1/15)
[19:05:25] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (2/15)
[19:05:26] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (3/15)
[19:05:26] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (4/15)
[19:05:26] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (5/15)
[19:05:26] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (6/15)
[19:05:26] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (7/15)
[19:05:27] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (8/15)
[19:05:27] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (9/15)
[19:05:27] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (10/15)
[19:05:27] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (11/15)
[19:05:28] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (12/15)
[19:05:28] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (13/15)
[19:05:28] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (14/15)
[19:05:28] [pool-26-thread-1/INFO]: [Vulcan] (player) failed Bad Packets (Type V) (15/15)
[19:05:28] [Server thread/INFO]: (player) lost connection: Kicked by Server: [Vulcan] Unfair Advantage
```

I have no idea what exactly this means. The Spigot page only lists: "Bad Packets: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y"

Vulcan page: https://www.spigotmc.org/resources/vulcan-anti-cheat-advanced-cheat-detection-1-7-1-19.83626/
Vulcan's Discord server (if needed, listed on their Spigot page): https://discord.gg/SCNuwUG

### Steps to reproduce the issue

1. Install and run Vulcan (premium) and CosmeticsCore
2. Make sure you have no Vulcan bypass permissions exempting you from flagging or punishments
3. Use `/wardrobe` and wait a few seconds until you get kicked.
4. Review console logs.

### Server version

This server is running Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version 1.0.0-beta1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by ProfessionalBoatDrifter** [comment]
I saw in the CosmeticsCore forums channel we should tag the developer of Vulcan. I _believe_ that their user name is @freppp judging by the link to their link to the config file from the Spigot page (https://gist.github.com/freppp/6f669d666835011f3661025c2d9533e2).

If the mention doesn't work: https://github.com/freppp

**Comment by LoneDev6** [comment]
Thanks!
Let's hope @freppp joins this chat and provides a little more detail about that.

**Comment by MelonCraftDE** [comment]
I'm using latest Paper and latest Vulcan release and i dont have to set up a bypass.
no issues for normal players, no kicks and also no false backpacket violations

as i can see you are not running latest versions. be sure to update first. maybe thats it.

**Comment by MelonCraftDE** [comment]
i have to revoke a bit from my last posting here.

we do have this issue too, but only with people who are using 1.19.1 clients
![image](https://user-images.githubusercontent.com/10966963/191313385-6679510c-6da8-448f-adea-45cf694de9a1.png)

**Comment by MelonCraftDE** [comment]
```
`[18:30:01] [Netty Epoll Server IO #0/ERROR]: [CosmeticsCore] Unhandled exception occurred in onPacketReceiving(PacketEvent) for CosmeticsCore
java.lang.NullPointerException: Cannot invoke "dev.lone.cosmeticscore.nms.aa.aa.e()" because "<local2>" is null
	at dev.lone.cosmeticscore.main.l.b(SourceFile:311) ~[CosmeticsCore_1.0.1-beta2.jar:?]
	at dev.lone.cosmeticscore.main.l.a(SourceFile:302) ~[CosmeticsCore_1.0.1-beta2.jar:?]
	at dev.lone.cosmeticscore.main.H.onPacketReceiving(SourceFile:169) ~[CosmeticsCore_1.0.1-beta2.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:549) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:514) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:117) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:506) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`
```

**Comment by ProfessionalBoatDrifter** [comment]
That's strange. I didn't see any errors when it happened to us

**Comment by MelonCraftDE** [comment]
Happened with bypass permission

Im sure its related to this, because it comes from the player thats shown
at the screenshot.
Maybe the further information in the screenshot and/or the error can help
LoneDev.

ProfessionalBoatDrifter ***@***.***> schrieb am Di., 20. Sep.
2022 20:24:

**Comment by LoneDev6** [comment]
Why in the first place are you allowing people with 1.19.1 clients?
Everyone must use the latest patch for the major client version, in this case 1.19.2.

1.17 -> 1.17.1
1.18 -> 1.18.2
1.19 -> 1.19.2

> [CosmeticsCore] Unhandled exception occurred in onPacketReceiving(PacketEvent) for CosmeticsCore

I doubt this is related to the anticheat, please open a separate issue report

> Thanks for the advice. :)
I'll consider it if the freppp hasn't replied by the time another Issue is resolve (which I haven't posted as of writing).

Is it working fine with 1.19.2 clients so? Let me know :D

**Comment by ProfessionalBoatDrifter** [comment]
> > Thanks for the advice. :)
> > I'll consider it if the freppp hasn't replied by the time another Issue is resolve (which I haven't posted as of writing).
> 
> Is it working fine with 1.19.2 clients so? Let me know :D

I just tested it on a debug server running only a few plugins (AntiPopup, EssentialsX, FAWE, LoneLibs, LuckPerms, Multiverse, PlaceholderAPI, ProtocolLib, Vault, VoidGen, Vulcan). `copied from Issue #16 since they are the same`

1.19.2 clients are still affected by Vulcan falsely flagging the player as cheating.

The server specs are still the same but I've copied over the current "/version" info just in case. `copied from Issue #16 since they are the same`
Server version: `Paper-160 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 8db45c4)`
CosmeticsCore version: `1.0.0-beta1`
LoneLibs version: `1.0.21`
ProtocolLib version: `5.0.0-SNAPSHOT-b600`

**Comment by ProfessionalBoatDrifter** [comment]
@LoneDev6 Screenshot from the Vulcan developer's support Discord: [https://prnt.sc/GOcgXIVqD4-L](url)

**Comment by ProfessionalBoatDrifter** [comment]
Boeing also linked me their API jar for you to decompile or use in your IDE: https://cdn.discordapp.com/attachments/1022171982890020995/1022188601116721294/VulcanAPI.jar

If you don't want to download it from the link, I'm sure they'll provide it if you join their Discord and open a ticket. :)

**Comment by ProfessionalBoatDrifter** [comment]
I just noticed this was closed. Shouldn't it be reopened? @LoneDev6

**Comment by LoneDev6** [comment]
Perfect, will be worked on

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/192720966-14ff0cc4-abef-4edb-87de-0eff6d057417.png)

**Comment by LoneDev6** [comment]
Contacted them on Discord, let's wait
